-- Delete Existing Table
DROP TABLE IF EXISTS Technology_Flavors;
-- Create New Table
CREATE TABLE Technology_Flavors ('TechType' text , 
								 'FlavorType' text , 
								 'Flavor' integer , foreign key (TechType) references Technologies(Type), foreign key (FlavorType) references Flavors(Type));
-- Polulate Table
INSERT INTO Technology_Flavors (	TechType,									FlavorType,									Flavor)
--ANCIENT ERA--
--SETTLER
SELECT								'TECH_WOOD_CLEARING',						'FLAVOR_TILE_IMPROVEMENT',					3							UNION ALL
SELECT								'TECH_WOOD_CLEARING',						'FLAVOR_OFFENSE',				         	5							UNION ALL
SELECT								'TECH_WOOD_CLEARING',						'FLAVOR_DEFENSE',				         	5							UNION ALL
SELECT								'TECH_FIRE',						        'FLAVOR_TILE_IMPROVEMENT',					3							UNION ALL
SELECT								'TECH_FIRE',						        'FLAVOR_EXPANSION',				         	5							UNION ALL
SELECT								'TECH_FIRE',						        'FLAVOR_SCIENCE',				         	2							UNION ALL
SELECT								'TECH_FIRE',						        'FLAVOR_GROWTH',				         	5							UNION ALL
SELECT								'TECH_HUNTING',					            'FLAVOR_GROWTH',							3							UNION ALL
SELECT								'TECH_HUNTING',					            'FLAVOR_MOBILE',                            4							UNION ALL
SELECT								'TECH_HUNTING',						        'FLAVOR_EXPANSION',				         	3							UNION ALL
SELECT								'TECH_SCOUTING',					        'FLAVOR_HAPPINESS',							2							UNION ALL
SELECT								'TECH_SCOUTING',					        'FLAVOR_OFFENSE',                           2							UNION ALL
SELECT								'TECH_SCOUTING',						    'FLAVOR_EXPANSION',				         	5							UNION ALL
SELECT								'TECH_SPORTS',					            'FLAVOR_HAPPINESS',							3							UNION ALL
SELECT								'TECH_SPORTS',						        'FLAVOR_EXPANSION',				         	4							UNION ALL
SELECT								'TECH_SPORTS',						        'FLAVOR_WONDER',				         	2							UNION ALL
SELECT								'TECH_TOOLS',					            'FLAVOR_PRODUCTION',					    2							UNION ALL
SELECT								'TECH_TOOLS',					            'FLAVOR_WONDER',                            3							UNION ALL
SELECT								'TECH_TOOLS',						        'FLAVOR_TILE_IMPROVEMENT',				    5							UNION ALL
SELECT								'TECH_TOOLS',						        'FLAVOR_HAPPINESS',				         	1							UNION ALL
SELECT								'TECH_CARAVANS',					        'FLAVOR_EXPANSION',					          3							UNION ALL
SELECT								'TECH_CARAVANS',					        'FLAVOR_GOLD',                                8							UNION ALL
SELECT								'TECH_CARAVANS',						    'FLAVOR_MOBILE',				              8							UNION ALL
SELECT								'TECH_CARAVANS',						    'FLAVOR_HAPPINESS',				              2							UNION ALL
SELECT							    'TECH_RAW_MATERIALS',					    'FLAVOR_EXPANSION',					          1						  	UNION ALL
SELECT								'TECH_RAW_MATERIALS',					    'FLAVOR_PRODUCTION',                          4							UNION ALL
SELECT								'TECH_RAW_MATERIALS',					    'FLAVOR_WONDER',				              2							UNION ALL
SELECT								'TECH_RAW_MATERIALS',					    'FLAVOR_TILE_IMPROVEMENT',		              1							UNION ALL
SELECT							    'TECH_FARMERS_MARKETS',					    'FLAVOR_GROWTH',,					          5						  	UNION ALL
SELECT								'TECH_FARMERS_MARKETS',					    'FLAVOR_SCIENCE',                             2							UNION ALL
SELECT								'TECH_FARMERS_MARKETS',						'FLAVOR_WONDER',				              2							UNION ALL
SELECT								'TECH_FARMERS_MARKETS',						'FLAVOR_EXPANSION',		                     2							UNION ALL
SELECT								'TECH_LANGUAGE',						    'FLAVOR_SCIENCE',				             5							UNION ALL
SELECT								'TECH_LANGUAGE',						    'FLAVOR_EXPANSION',		                     5							UNION ALL

SELECT								'TECH_AGRICULTURE',							'FLAVOR_GROWTH',							5							UNION ALL
SELECT								'TECH_CALENDAR',							'FLAVOR_WONDER',							4							UNION ALL
SELECT								'TECH_CALENDAR',							'FLAVOR_RELIGION',							10							UNION ALL
SELECT								'TECH_CALENDAR',							'FLAVOR_HAPPINESS',							4							UNION ALL
SELECT								'TECH_CALENDAR',							'FLAVOR_CULTURE',							1							UNION ALL
SELECT								'TECH_CALENDAR',							'FLAVOR_SCIENCE',							2							UNION ALL
SELECT								'TECH_CALENDAR',							'FLAVOR_OFFENSE',							1							UNION ALL
SELECT								'TECH_CALENDAR',							'FLAVOR_EXPANSION',							2							UNION ALL
SELECT								'TECH_ANIMAL_HUSBANDRY',					'FLAVOR_GROWTH',							2							UNION ALL
SELECT								'TECH_ANIMAL_HUSBANDRY',					'FLAVOR_MOBILE',							8							UNION ALL
SELECT								'TECH_ANIMAL_HUSBANDRY',					'FLAVOR_PRODUCTION',						4							UNION ALL
SELECT								'TECH_ANIMAL_HUSBANDRY',					'FLAVOR_TILE_IMPROVEMENT',					3							UNION ALL
SELECT								'TECH_MINING',								'FLAVOR_PRODUCTION',						8							UNION ALL
SELECT								'TECH_MINING',								'FLAVOR_TILE_IMPROVEMENT',					5							UNION ALL
SELECT								'TECH_POTTERY',								'FLAVOR_WONDER',							2							UNION ALL
SELECT								'TECH_POTTERY',								'FLAVOR_INFRASTRUCTURE',					2							UNION ALL
SELECT								'TECH_POTTERY',								'FLAVOR_GROWTH',							12							UNION ALL
SELECT								'TECH_THE_WHEEL',							'FLAVOR_GROWTH',							1							UNION ALL
SELECT								'TECH_THE_WHEEL',							'FLAVOR_EXPANSION',							1							UNION ALL
SELECT								'TECH_THE_WHEEL',							'FLAVOR_PRODUCTION',						2							UNION ALL
SELECT								'TECH_THE_WHEEL',							'FLAVOR_INFRASTRUCTURE',					6							UNION ALL
SELECT								'TECH_THE_WHEEL',							'FLAVOR_GOLD',								2							UNION ALL
SELECT								'TECH_MASONRY',								'FLAVOR_CITY_DEFENSE',						6							UNION ALL
SELECT								'TECH_MASONRY',								'FLAVOR_TILE_IMPROVEMENT',					5							UNION ALL
SELECT								'TECH_MASONRY',								'FLAVOR_WONDER',							2							UNION ALL
SELECT								'TECH_MASONRY',								'FLAVOR_PRODUCTION',						1							UNION ALL

--NOMAD

SELECT								'TECH_FISH_MARKETS',						'FLAVOR_NAVAL',								4							UNION ALL
SELECT								'TECH_FISH_MARKETS',						'FLAVOR_NAVAL_TILE_IMPROVEMENT',			10							UNION ALL
SELECT								'TECH_FISH_MARKETS',						'FLAVOR_NAVAL_GROWTH',						2							UNION ALL
SELECT								'TECH_FISH_MARKETS',						'FLAVOR_GROWTH',						    3							UNION ALL
SELECT								'TECH_SOCIAL_STRUCTURE',					'FLAVOR_GOLD',								2							UNION ALL
SELECT								'TECH_SOCIAL_STRUCTURE',					'FLAVOR_GROWTH',							5							UNION ALL
SELECT								'TECH_SOCIAL_STRUCTURE',					'FLAVOR_EXPANSION',					       10							UNION ALL
SELECT								'TECH_SOCIAL_STRUCTURE',					'FLAVOR_HAPPINESS',							2							UNION ALL
SELECT								'TECH_SOCIAL_STRUCTURE',					'FLAVOR_SCIENCE',							2							UNION ALL
SELECT								'TECH_WARFARE',								'FLAVOR_DEFENSE',						   4							UNION ALL
SELECT								'TECH_WARFARE',								'FLAVOR_MILITARY_TRAINING',			       5							UNION ALL
SELECT								'TECH_WARFARE',								'FLAVOR_OFFENSE',						   8							UNION ALL
SELECT								'TECH_LEADERSHIP',							'FLAVOR_DEFENSE',						   5							UNION ALL
SELECT								'TECH_LEADERSHIP',							'FLAVOR_EXPANSION',			               10							UNION ALL
SELECT								'TECH_LEADERSHIP',							'FLAVOR_GROWTH',						   5							UNION ALL
SELECT								'TECH_LEADERSHIP',							'FLAVOR_WONDER',			              10							UNION ALL
SELECT								'TECH_LEADERSHIP',							'FLAVOR_SCIENCE',						   5							UNION ALL
SELECT								'TECH_LEADERSHIP',							'FLAVOR_PRODUCTION',			           5							UNION ALL
SELECT								'TECH_LEADERSHIP',							'FLAVOR_CULTURE',			               5							UNION ALL
SELECT								'TECH_COPPER_WORKING',						'FLAVOR_TILE_IMPROVEMENT',				   3							UNION ALL
SELECT								'TECH_COPPER_WORKING',						'FLAVOR_WONDER',			               3							UNION ALL
SELECT								'TECH_COPPER_WORKING',						'FLAVOR_PRODUCTION',					   4							UNION ALL
SELECT								'TECH_TRIBAL_WARRIOR',					    'FLAVOR_OFFENSE',							2							UNION ALL
SELECT								'TECH_TRIBAL_WARRIOR',					    'FLAVOR_DEFENSE',							1							UNION ALL
SELECT								'TECH_TRIBAL_WARRIOR',					    'FLAVOR_MILITARY_TRAINING',					5							UNION ALL

SELECT								'TECH_SAILING',								'FLAVOR_NAVAL',								4							UNION ALL
SELECT								'TECH_SAILING',								'FLAVOR_NAVAL_TILE_IMPROVEMENT',			10							UNION ALL
SELECT								'TECH_SAILING',								'FLAVOR_NAVAL_GROWTH',						2							UNION ALL
SELECT								'TECH_SHIPBUILDING',						'FLAVOR_NAVAL',								8							UNION ALL
SELECT								'TECH_SHIPBUILDING',						'FLAVOR_NAVAL_RECON',						6							UNION ALL
SELECT								'TECH_ECONOMY_OF_SCALE',					'FLAVOR_GOLD',								4							UNION ALL
SELECT								'TECH_ECONOMY_OF_SCALE',					'FLAVOR_GROWTH',							4							UNION ALL
SELECT								'TECH_ECONOMY_OF_SCALE',					'FLAVOR_TILE_IMPROVEMENT',					3							UNION ALL
SELECT								'TECH_ECONOMY_OF_SCALE',					'FLAVOR_HAPPINESS',							10							UNION ALL
SELECT								'TECH_TRADING',								'FLAVOR_TILE_IMPROVEMENT',					5							UNION ALL
SELECT								'TECH_TRADING',								'FLAVOR_GOLD',								12							UNION ALL
SELECT								'TECH_FERMENTATION',						'FLAVOR_HAPPINESS',							2							UNION ALL
SELECT								'TECH_FERMENTATION',						'FLAVOR_GROWTH',							2							UNION ALL
SELECT								'TECH_FERMENTATION',						'FLAVOR_TILE_IMPROVEMENT',					1							UNION ALL
SELECT								'TECH_FERMENTATION',						'FLAVOR_EXPANSION',							2							UNION ALL
SELECT								'TECH_TRAPPING',							'FLAVOR_GOLD',								4							UNION ALL
SELECT								'TECH_TRAPPING',							'FLAVOR_GROWTH',							2							UNION ALL
SELECT								'TECH_TRAPPING',							'FLAVOR_TILE_IMPROVEMENT',					3							UNION ALL
SELECT								'TECH_TRAPPING',							'FLAVOR_HAPPINESS',							6							UNION ALL
SELECT								'TECH_ARCHERY',								'FLAVOR_RANGED',							4							UNION ALL
SELECT								'TECH_ARCHERY',								'FLAVOR_OFFENSE',							1							UNION ALL
SELECT								'TECH_ARCHERY',								'FLAVOR_DEFENSE',							2							UNION ALL
SELECT								'TECH_BRONZE_WORKING',						'FLAVOR_DEFENSE',							8							UNION ALL
SELECT								'TECH_BRONZE_WORKING',						'FLAVOR_TILE_IMPROVEMENT',					1							UNION ALL
SELECT								'TECH_BRONZE_WORKING',						'FLAVOR_WONDER',							2							UNION ALL
SELECT								'TECH_BRONZE_WORKING',						'FLAVOR_OFFENSE',							2							UNION ALL
SELECT								'TECH_MILITARY_TRAINING',					'FLAVOR_OFFENSE',							2							UNION ALL
SELECT								'TECH_MILITARY_TRAINING',					'FLAVOR_DEFENSE',							1							UNION ALL
SELECT								'TECH_MILITARY_TRAINING',					'FLAVOR_MILITARY_TRAINING',					10							UNION ALL

--SPIRIT

SELECT								'TECH_FOLKLORE',							'FLAVOR_WONDER',							1							UNION ALL
SELECT								'TECH_FOLKLORE',							'FLAVOR_RELIGION',							1							UNION ALL
SELECT								'TECH_FOLKLORE',							'FLAVOR_CULTURE',							5							UNION ALL
SELECT								'TECH_MUMMIFICATION',						'FLAVOR_WONDER',							6							UNION ALL
SELECT								'TECH_MUMMIFICATION',						'FLAVOR_RELIGION',							2							UNION ALL
SELECT								'TECH_MUMMIFICATION',						'FLAVOR_CULTURE',							4							UNION ALL
SELECT								'TECH_RITUALS',						        'FLAVOR_OFFENSE',							2							UNION ALL
SELECT								'TECH_RITUALS',						        'FLAVOR_RELIGION',							3							UNION ALL
SELECT								'TECH_RITUALS',						        'FLAVOR_CULTURE',							3							UNION ALL
SELECT								'TECH_RITUALS',						        'FLAVOR_SCIENCE',							1							UNION ALL
SELECT								'TECH_ART',						            'FLAVOR_WONDER',							4							UNION ALL
SELECT								'TECH_ART',						            'FLAVOR_HAPPINESS',							1							UNION ALL
SELECT								'TECH_ART',						            'FLAVOR_CULTURE',							4							UNION ALL
SELECT								'TECH_IDOLS',						        'FLAVOR_RELIGION',							2							UNION ALL
SELECT								'TECH_IDOLS',						        'FLAVOR_HAPPINESS',							1							UNION ALL
SELECT								'TECH_IDOLS',						        'FLAVOR_CULTURE',							1							UNION ALL



SELECT								'TECH_ORAL_TRADITION',						'FLAVOR_SCIENCE',							3							UNION ALL
SELECT								'TECH_ORAL_TRADITION',						'FLAVOR_GOLD',								4							UNION ALL
SELECT								'TECH_ORAL_TRADITION',						'FLAVOR_CITY_DEFENSE',						1							UNION ALL
SELECT								'TECH_CEREMONIAL_BURIAL',					'FLAVOR_CULTURE',							6							UNION ALL
SELECT								'TECH_GREAT_MONUMENTS',						'FLAVOR_WONDER',							9							UNION ALL
SELECT								'TECH_GREAT_MONUMENTS',						'FLAVOR_CULTURE',							2							UNION ALL
SELECT								'TECH_MYSTICISM',							'FLAVOR_RELIGION',							10							UNION ALL
SELECT								'TECH_MYSTICISM',							'FLAVOR_HAPPINESS',							2							UNION ALL
SELECT								'TECH_MYSTICISM',							'FLAVOR_INFRASTRUCTURE',					2							UNION ALL
SELECT								'TECH_MYSTICISM',							'FLAVOR_WONDER',							2							UNION ALL
SELECT								'TECH_MEDITATION',							'FLAVOR_WONDER',							4							UNION ALL
SELECT								'TECH_MEDITATION',							'FLAVOR_RELIGION',							6							UNION ALL
SELECT								'TECH_MEDITATION',							'FLAVOR_SCIENCE',							3							UNION ALL



--CLASSICAL ERA--
--NUMBER THEORY

SELECT								'TECH_VASALAGE',							'FLAVOR_GOLD',								3							UNION ALL
SELECT								'TECH_VASALAGE',							'FLAVOR_HAPPINESS',							2							UNION ALL
SELECT								'TECH_VASALAGE',							'FLAVOR_WONDER',							7							UNION ALL
SELECT								'TECH_CASTE_SYSTEM',						'FLAVOR_CULTURE',							2							UNION ALL
SELECT								'TECH_CASTE_SYSTEM',						'FLAVOR_DIPLOMACY',							10							UNION ALL
SELECT								'TECH_CASTE_SYSTEM',						'FLAVOR_RELIGION',							1							UNION ALL
SELECT								'TECH_CASTE_SYSTEM',						'FLAVOR_WONDER',							7							UNION ALL
SELECT								'TECH_SLAVERY',						        'FLAVOR_PRODUCTION',						10							UNION ALL
SELECT								'TECH_SLAVERY',						        'FLAVOR_GOLD',							    1							UNION ALL
SELECT								'TECH_SLAVERY',						        'FLAVOR_EXPANSION',							1							UNION ALL
SELECT								'TECH_SLAVERY',						        'FLAVOR_WONDER',							3							UNION ALL
SELECT								'TECH_LODGING',						        'FLAVOR_INFRASTRUCTURE',					2							UNION ALL
SELECT								'TECH_LODGING',						        'FLAVOR_GOLD',							    8							UNION ALL
SELECT								'TECH_LODGING',						        'FLAVOR_EXPANSION',							3							UNION ALL
SELECT								'TECH_LODGING',						        'FLAVOR_HAPPINESS',							4							UNION ALL
SELECT								'TECH_LODGING',						        'FLAVOR_CULTURE',							2							UNION ALL
SELECT								'TECH_CALCULUS',							'FLAVOR_WONDER',							7							UNION ALL
SELECT								'TECH_CALCULUS',							'FLAVOR_SCIENCE',							1							UNION ALL
SELECT								'TECH_CALCULUS',							'FLAVOR_CULTURE',							3							UNION ALL
SELECT								'TECH_CALCULUS',							'FLAVOR_RELIGION',							5							UNION ALL

SELECT								'TECH_CARRIAGES',							'FLAVOR_HAPPINESS',							8							UNION ALL
SELECT								'TECH_CARRIAGES',							'FLAVOR_OFFENSE',							1							UNION ALL
SELECT								'TECH_CARRIAGES',							'FLAVOR_RANGED',							4							UNION ALL
SELECT								'TECH_CARRIAGES',							'FLAVOR_MOBILE',							4							UNION ALL
SELECT								'TECH_CARRIAGES',							'FLAVOR_DEFENSE',							3							UNION ALL
SELECT								'TECH_HORSEBACK_RIDING',					'FLAVOR_MOBILE',							10							UNION ALL
SELECT								'TECH_HORSEBACK_RIDING',					'FLAVOR_OFFENSE',							5							UNION ALL
SELECT								'TECH_HORSEBACK_RIDING',					'FLAVOR_PRODUCTION',						2							UNION ALL
SELECT								'TECH_HORSEBACK_RIDING',					'FLAVOR_TILE_IMPROVEMENT',					1							UNION ALL
SELECT								'TECH_MATHEMATICS',							'FLAVOR_WONDER',							2							UNION ALL
SELECT								'TECH_MATHEMATICS',							'FLAVOR_RELIGION',							1							UNION ALL
SELECT								'TECH_MATHEMATICS',							'FLAVOR_CULTURE',							1							UNION ALL
SELECT								'TECH_MATHEMATICS',							'FLAVOR_SCIENCE',							4							UNION ALL
SELECT								'TECH_CURRENCY',							'FLAVOR_GOLD',								10							UNION ALL
SELECT								'TECH_CURRENCY',							'FLAVOR_HAPPINESS',							2							UNION ALL
SELECT								'TECH_CURRENCY',							'FLAVOR_WONDER',							2							UNION ALL

--ALPHABET

SELECT								'TECH_CUNEIFORM',							'FLAVOR_SCIENCE',							10							UNION ALL
SELECT								'TECH_CUNEIFORM',							'FLAVOR_WONDER',							2							UNION ALL
SELECT								'TECH_CUNEIFORM',							'FLAVOR_DIPLOMACY',							2							UNION ALL
SELECT								'TECH_CUNEIFORM',							'FLAVOR_GOLD',							    1							UNION ALL
SELECT								'TECH_CUNEIFORM',							'FLAVOR_PRODUCTION',						1							UNION ALL
SELECT								'TECH_CLERGY',							    'FLAVOR_RELIGION',							10							UNION ALL
SELECT								'TECH_CLERGY',							    'FLAVOR_WONDER',							5							UNION ALL
SELECT								'TECH_CLERGY',							    'FLAVOR_CULTURE',							2							UNION ALL
SELECT								'TECH_CLERGY',					            'FLAVOR_TILE_IMPROVEMENT',					1							UNION ALL
SELECT								'TECH_HOLY_ORDERS',							'FLAVOR_CULTURE',							1							UNION ALL
SELECT								'TECH_HOLY_ORDERS',							'FLAVOR_RELIGION',						   10							UNION ALL
SELECT								'TECH_HOLY_ORDERS',							'FLAVOR_HAPPINESS',						    3							UNION ALL
SELECT								'TECH_HOLY_ORDERS',							'FLAVOR_TILE_IMPROVEMENT',					1							UNION ALL
SELECT								'TECH_HOLY_ORDERS',							'FLAVOR_WONDER',					        5							UNION ALL
SELECT								'TECH_CONSULATES',							'FLAVOR_CULTURE',							4							UNION ALL
SELECT								'TECH_CONSULATES',							'FLAVOR_RELIGION',						    4							UNION ALL
SELECT								'TECH_CONSULATES',							'FLAVOR_DIPLOMAMACY',					   12							UNION ALL
SELECT								'TECH_CONSULATES',							'FLAVOR_WONDER',					        5							UNION ALL

SELECT								'TECH_WRITING',								'FLAVOR_SCIENCE',							12							UNION ALL
SELECT								'TECH_WRITING',								'FLAVOR_WONDER',							2							UNION ALL
SELECT								'TECH_WRITING',								'FLAVOR_DIPLOMACY',							2							UNION ALL
SELECT								'TECH_PHILOSOPHY',							'FLAVOR_SCIENCE',							8							UNION ALL
SELECT								'TECH_PHILOSOPHY',							'FLAVOR_CULTURE',							6							UNION ALL
SELECT								'TECH_PHILOSOPHY',							'FLAVOR_RELIGION',							1							UNION ALL
SELECT								'TECH_PHILOSOPHY',							'FLAVOR_WONDER',							6							UNION ALL
SELECT								'TECH_POETRY',								'FLAVOR_MILITARY_TRAINING',					4							UNION ALL
SELECT								'TECH_POETRY',								'FLAVOR_WONDER',							2							UNION ALL
SELECT								'TECH_POETRY',								'FLAVOR_CULTURE',							1							UNION ALL
SELECT								'TECH_POETRY',								'FLAVOR_GOLD',								2							UNION ALL
SELECT								'TECH_POETRY',								'FLAVOR_TILE_IMPROVEMENT',					1							UNION ALL
SELECT								'TECH_PRIESTHOOD',							'FLAVOR_HAPPINESS',							2							UNION ALL
SELECT								'TECH_PRIESTHOOD',							'FLAVOR_RELIGION',							12							UNION ALL
SELECT								'TECH_PRIESTHOOD',							'FLAVOR_GOLD',								1							UNION ALL
SELECT								'TECH_CODE_OF_LAWS',						'FLAVOR_HAPPINESS',							4							UNION ALL
SELECT								'TECH_CODE_OF_LAWS',						'FLAVOR_EXPANSION',							10							UNION ALL
SELECT								'TECH_CODE_OF_LAWS',						'FLAVOR_GROWTH',							4							UNION ALL
SELECT								'TECH_CODE_OF_LAWS',						'FLAVOR_WONDER',							2							UNION ALL

--ARTISANS

SELECT								'TECH_HEROISM',						        'FLAVOR_OFFENSE',							5							UNION ALL
SELECT								'TECH_HEROISM',						        'FLAVOR_DEFENSE',							5							UNION ALL
SELECT								'TECH_HEROISM',						        'FLAVOR_WONDER',							3							UNION ALL
SELECT								'TECH_HEROISM',						        'FLAVOR_TILE_IMPROVEMENT',					2							UNION ALL
SELECT								'TECH_HEROISM',					            'FLAVOR_MILITARY_TRAINING',				    7							UNION ALL
SELECT								'TECH_GOVERNMENT',						    'FLAVOR_EXPANSION',						    6							UNION ALL
SELECT								'TECH_GOVERNMENT',						    'FLAVOR_GROWTH',							4							UNION ALL
SELECT								'TECH_GOVERNMENT',						    'FLAVOR_HAPPINESS',						    4							UNION ALL
SELECT								'TECH_GOVERNMENT',						    'FLAVOR_WONDER',						    2							UNION ALL
SELECT								'TECH_GOVERNMENT',						    'FLAVOR_CULTURE',						    1							UNION ALL
SELECT								'TECH_FORTIFICATION',						 'FLAVOR_OFFENSE',							5							UNION ALL
SELECT								'TECH_FORTIFICATION',					     'FLAVOR_DEFENSE',							8							UNION ALL
SELECT								'TECH_FORTIFICATION',					     'FLAVOR_MILITARY_TRAINING',				3							UNION ALL
SELECT								'TECH_FORTIFICATION',						 'FLAVOR_WONDER',						    2							UNION ALL
SELECT								'TECH_FORTIFICATION',						 'FLAVOR_CITY_DEFENSE',						10						    UNION ALL					
SELECT								'TECH_FORTIFICATION',					     'FLAVOR_TILE_IMPROVEMENT',					2							UNION ALL
SELECT								'TECH_SANITATION',					         'FLAVOR_GROWTH',				            10							UNION ALL
SELECT								'TECH_SANITATION',						     'FLAVOR_HAPPINESS',					     5							UNION ALL
SELECT								'TECH_SANITATION',						     'FLAVOR_SCIENCE',						     3						    UNION ALL					
SELECT								'TECH_SANITATION',					         'FLAVOR_EXPANSION',					     2							UNION ALL
SELECT								'TECH_SIEGE_WARFARE'					      'FLAVOR_PRODUCTION',				         3						    UNION ALL
SELECT								'TECH_SIEGE_WARFARE'						  'FLAVOR_MILITARY_TRAINING',				 5							UNION ALL
SELECT								'TECH_SIEGE_WARFARE'						  'FLAVOR_OFFENSE',							 10						    UNION ALL					
SELECT								'TECH_SIEGE_WARFARE'				          'FLAVOR_MILITARY_TRAINING',				 3						    UNION ALL

SELECT								'TECH_CONSTRUCTION',						'FLAVOR_HAPPINESS',							10							UNION ALL
SELECT								'TECH_CONSTRUCTION',						'FLAVOR_PRODUCTION',						1							UNION ALL
SELECT								'TECH_CONSTRUCTION',						'FLAVOR_GOLD',								1							UNION ALL
SELECT								'TECH_CONSTRUCTION',						'FLAVOR_EXPANSION',							4							UNION ALL
SELECT								'TECH_CONSTRUCTION',						'FLAVOR_TILE_IMPROVEMENT',					3							UNION ALL
SELECT								'TECH_WOODWORKING',							'FLAVOR_RANGED',							8							UNION ALL
SELECT								'TECH_WOODWORKING',							'FLAVOR_OFFENSE',							6							UNION ALL
SELECT								'TECH_WOODWORKING',							'FLAVOR_DEFENSE',							3							UNION ALL
SELECT								'TECH_PUBLIC_WORKS',						'FLAVOR_HAPPINESS',							4							UNION ALL
SELECT								'TECH_PUBLIC_WORKS',						'FLAVOR_GROWTH',							4							UNION ALL
SELECT								'TECH_PUBLIC_WORKS',						'FLAVOR_WONDER',							2							UNION ALL
SELECT								'TECH_PUBLIC_WORKS',						'FLAVOR_CULTURE',							6							UNION ALL
SELECT								'TECH_DIVISION_OF_LABOR',					'FLAVOR_PRODUCTION',						10							UNION ALL
SELECT								'TECH_DIVISION_OF_LABOR',					'FLAVOR_GOLD',								4							UNION ALL
SELECT								'TECH_DIVISION_OF_LABOR',					'FLAVOR_INFRASTRUCTURE',					2							UNION ALL
SELECT								'TECH_DIVISION_OF_LABOR',					'FLAVOR_OFFENSE',							1							UNION ALL
SELECT								'TECH_DIVISION_OF_LABOR',					'FLAVOR_GROWTH',							3							UNION ALL
SELECT								'TECH_IRON_WORKING',						'FLAVOR_OFFENSE',							12							UNION ALL
SELECT								'TECH_IRON_WORKING',						'FLAVOR_DEFENSE',							3							UNION ALL
SELECT								'TECH_IRON_WORKING',						'FLAVOR_WONDER',							2							UNION ALL
SELECT								'TECH_IRON_WORKING',						'FLAVOR_NAVAL_TILE_IMPROVEMENT',			2							UNION ALL
SELECT								'TECH_IRON_WORKING',						'FLAVOR_PRODUCTION',						2							UNION ALL
SELECT								'TECH_OPTICS',								'FLAVOR_NAVAL',								2							UNION ALL
SELECT								'TECH_OPTICS',								'FLAVOR_SCIENCE',							4							UNION ALL
SELECT								'TECH_OPTICS',								'FLAVOR_NAVAL_GROWTH',						6							UNION ALL



--MEDIEVAL ERA--
--EXOTIC GOODS
SELECT								'TECH_RUBBER',					           'FLAVOR_TILE_IMPROVEMENT',					2							UNION ALL
SELECT								'TECH_RUBBER',				               'FLAVOR_SCIENCE',						    2							UNION ALL


SELECT								'TECH_LUXURY_GOODS',			            'FLAVOR_EXPANSION',						    5							UNION ALL
SELECT								'TECH_LUXURY_GOODS',			            'FLAVOR_TILE_IMPROVEMENT',					2							UNION ALL
SELECT								'TECH_LUXURY_GOODS',			            'FLAVOR_HAPPINESS',						   10							UNION ALL
SELECT								'TECH_LUXURY_GOODS',			            'FLAVOR_GROWTH',							5							UNION ALL
SELECT								'TECH_AGRICULTURAL_ENGINEERING',			'FLAVOR_WONDER',							6							UNION ALL
SELECT								'TECH_AGRICULTURAL_ENGINEERING',			'FLAVOR_TILE_IMPROVEMENT',					2							UNION ALL
SELECT								'TECH_AGRICULTURAL_ENGINEERING',			'FLAVOR_PRODUCTION',						10							UNION ALL
SELECT								'TECH_AGRICULTURAL_ENGINEERING',			'FLAVOR_GROWTH',							10							UNION ALL
SELECT								'TECH_CRAFTSMAN',				            'FLAVOR_HAPPINESS',				            1							UNION ALL
SELECT								'TECH_CRAFTSMAN',				            'FLAVOR_CULTURE',				            1							UNION ALL
SELECT								'TECH_CRAFTSMAN',				            'FLAVOR_RELIGION',							1							UNION ALL
SELECT								'TECH_CRAFTSMAN',				            'FLAVOR_WONDER',					        8							UNION ALL
SELECT								'TECH_CRAFTSMAN',				            'FLAVOR_PRODUCTION',						5							UNION ALL
SELECT								'TECH_CRAFTSMAN',				            'FLAVOR_MILITARY_TRAINING',				    5							UNION ALL
SELECT								'TECH_TOBACCO_TRADING',				       'FLAVOR_GOLD',								2							UNION ALL
SELECT								'TECH_TOBACCO_TRADING',				       'FLAVOR_TILE_IMPROVEMENT',					2							UNION ALL
SELECT								'TECH_TOBACCO_TRADING',				       'FLAVOR_SCIENCE',						    2							UNION ALL

SELECT								'TECH_AGRICULTURAL_REVOLUTION',				'FLAVOR_GOLD',								2							UNION ALL
SELECT								'TECH_AGRICULTURAL_REVOLUTION',				'FLAVOR_TILE_IMPROVEMENT',					2							UNION ALL
SELECT								'TECH_AGRICULTURAL_REVOLUTION',				'FLAVOR_PRODUCTION',						2							UNION ALL
SELECT								'TECH_AGRICULTURAL_REVOLUTION',				'FLAVOR_GROWTH',							15							UNION ALL
SELECT								'TECH_COFFEE_TRADE',						'FLAVOR_GOLD',								3							UNION ALL
SELECT								'TECH_COFFEE_TRADE',						'FLAVOR_TILE_IMPROVEMENT',					2							UNION ALL
SELECT								'TECH_COFFEE_TRADE',						'FLAVOR_SCIENCE',							4							UNION ALL
SELECT								'TECH_TRADE_FAIRS',							'FLAVOR_GOLD',								10							UNION ALL
SELECT								'TECH_TRADE_FAIRS',							'FLAVOR_WONDER',							2							UNION ALL
SELECT								'TECH_TRADE_FAIRS',							'FLAVOR_GROWTH',							2							UNION ALL
SELECT								'TECH_TRADE_FAIRS',							'FLAVOR_PRODUCTION',						1							UNION ALL
SELECT								'TECH_TRADE_FAIRS',							'FLAVOR_TILE_IMPROVEMENT',					3							UNION ALL
SELECT								'TECH_BONDS',								'FLAVOR_WONDER',							2							UNION ALL
SELECT								'TECH_BONDS',								'FLAVOR_GOLD',								14							UNION ALL
SELECT								'TECH_METALLURGY',							'FLAVOR_OFFENSE',							12							UNION ALL
SELECT								'TECH_METALLURGY',							'FLAVOR_DEFENSE',							4							UNION ALL
SELECT								'TECH_METALLURGY',							'FLAVOR_PRODUCTION',						2							UNION ALL
SELECT								'TECH_METALLURGY',							'FLAVOR_GOLD',								1							UNION ALL
SELECT								'TECH_METALLURGY',							'FLAVOR_TILE_IMPROVEMENT',					2							UNION ALL
SELECT								'TECH_CIVIL_SERVICE',						'FLAVOR_WONDER',							2							UNION ALL
SELECT								'TECH_CIVIL_SERVICE',						'FLAVOR_GROWTH',							4							UNION ALL
SELECT								'TECH_CIVIL_SERVICE',						'FLAVOR_PRODUCTION',						1							UNION ALL
SELECT								'TECH_CIVIL_SERVICE',						'FLAVOR_GOLD',								1							UNION ALL
SELECT								'TECH_CIVIL_SERVICE',						'FLAVOR_SCIENCE',							1							UNION ALL
SELECT								'TECH_CIVIL_SERVICE',						'FLAVOR_DIPLOMACY',							8							UNION ALL
SELECT								'TECH_CIVIL_SERVICE',						'FLAVOR_TILE_IMPROVEMENT',					1							UNION ALL

--MEDIEVAL UNIVERSITY



SELECT								'TECH_MARTIAL_ARTS',						'FLAVOR_CULTURE',							2							UNION ALL
SELECT								'TECH_MARTIAL_ARTS',						'FLAVOR_WONDER',							6							UNION ALL
SELECT								'TECH_MARTIAL_ARTS',						'FLAVOR_MILITARY_TRAINING',					6							UNION ALL
SELECT								'TECH_MARTIAL_ARTS',						'FLAVOR_OFFENSE',							2							UNION ALL
SELECT								'TECH_MARTIAL_ARTS',						'FLAVOR_DEFENSE',							2							UNION ALL
SELECT								'TECH_ACOUSTICS_ENGINEERING',				'FLAVOR_CULTURE',							10							UNION ALL
SELECT								'TECH_ACOUSTICS_ENGINEERING',				'FLAVOR_WONDER',							10							UNION ALL
SELECT								'TECH_ACOUSTICS_ENGINEERING',				'FLAVOR_HAPPINESS',							4							UNION ALL
SELECT								'TECH_ACOUSTICS_ENGINEERING',				'FLAVOR_RELIGION',							5							UNION ALL
SELECT								'TECH_SACRED_ART',				            'FLAVOR_CULTURE',							10							UNION ALL
SELECT								'TECH_SACRED_ART',				            'FLAVOR_WONDER',							10							UNION ALL
SELECT								'TECH_SACRED_ART',				            'FLAVOR_HAPPINESS',							1							UNION ALL
SELECT								'TECH_SACRED_ART',				            'FLAVOR_RELIGION',							10							UNION ALL
SELECT								'TECH_CARNIVAL',				            'FLAVOR_CULTURE',							5							UNION ALL
SELECT								'TECH_CARNIVAL',				            'FLAVOR_WONDER',							10							UNION ALL
SELECT								'TECH_CARNIVAL',				            'FLAVOR_HAPPINESS',							6							UNION ALL
SELECT								'TECH_CARNIVAL',				            'FLAVOR_RELIGION',							5							UNION ALL
SELECT								'TECH_RELIGIOUS_STUDIES',				     'FLAVOR_CULTURE',							5							UNION ALL
SELECT								'TECH_RELIGIOUS_STUDIES',				     'FLAVOR_WONDER',							10							UNION ALL
SELECT								'TECH_RELIGIOUS_STUDIES',				     'FLAVOR_HAPPINESS',						1							UNION ALL
SELECT								'TECH_RELIGIOUS_STUDIES',				     'FLAVOR_RELIGION',							15							UNION ALL
SELECT								'TECH_CRUSADE',				                 'FLAVOR_MILITARY_TRAINING',				8							UNION ALL
SELECT								'TECH_CRUSADE',				                 'FLAVOR_WONDER',							8							UNION ALL
SELECT								'TECH_CRUSADE',				                 'FLAVOR_DEFENSE',							8							UNION ALL
SELECT								'TECH_CRUSADE',				                 'FLAVOR_RELIGION',							6							UNION ALL
SELECT								'TECH_CRUSADE',				                 'FLAVOR_OFFENSE',							8							UNION ALL


SELECT								'TECH_LITERATURE',							'FLAVOR_CULTURE',							12							UNION ALL
SELECT								'TECH_LITERATURE',							'FLAVOR_WONDER',							4							UNION ALL
SELECT								'TECH_LITERATURE',							'FLAVOR_HAPPINESS',							4							UNION ALL
SELECT								'TECH_FEUDALISM',							'FLAVOR_DEFENSE',							8							UNION ALL
SELECT								'TECH_FEUDALISM',							'FLAVOR_WONDER',							4							UNION ALL
SELECT								'TECH_FEUDALISM',							'FLAVOR_CITY_DEFENSE',						4							UNION ALL
SELECT								'TECH_FEUDALISM',							'FLAVOR_MILITARY_TRAINING',					1							UNION ALL
SELECT								'TECH_CHIVALRY',							'FLAVOR_OFFENSE',							5							UNION ALL
SELECT								'TECH_CHIVALRY',							'FLAVOR_MOBILE',							10							UNION ALL
SELECT								'TECH_CHIVALRY',							'FLAVOR_CITY_DEFENSE',						6							UNION ALL
SELECT								'TECH_CHIVALRY',							'FLAVOR_WONDER',							2							UNION ALL
SELECT								'TECH_CHIVALRY',							'FLAVOR_DIPLOMACY',							4							UNION ALL
SELECT								'TECH_FUNDAMENTALISM',						'FLAVOR_WONDER',							4							UNION ALL
SELECT								'TECH_FUNDAMENTALISM',						'FLAVOR_GOLD',								2							UNION ALL
SELECT								'TECH_FUNDAMENTALISM',						'FLAVOR_HAPPINESS',							4							UNION ALL
SELECT								'TECH_FUNDAMENTALISM',						'FLAVOR_RELIGION',							4							UNION ALL
SELECT								'TECH_DRAMA',								'FLAVOR_EXPANSION',							4							UNION ALL
SELECT								'TECH_DRAMA',								'FLAVOR_HAPPINESS',							10							UNION ALL
SELECT								'TECH_DRAMA',								'FLAVOR_CULTURE',							4							UNION ALL
SELECT								'TECH_DRAMA',								'FLAVOR_GREAT_PEOPLE',						2							UNION ALL
SELECT								'TECH_ACOUSTICS',							'FLAVOR_CULTURE',							10							UNION ALL
SELECT								'TECH_ACOUSTICS',							'FLAVOR_WONDER',							4							UNION ALL
SELECT								'TECH_ACOUSTICS',							'FLAVOR_RELIGION',							10							UNION ALL
SELECT								'TECH_ACOUSTICS',							'FLAVOR_HAPPINESS',							4							UNION ALL
SELECT								'TECH_THEOLOGY',							'FLAVOR_RELIGION',							14							UNION ALL
SELECT								'TECH_THEOLOGY',							'FLAVOR_GREAT_PEOPLE',						1							UNION ALL
SELECT								'TECH_THEOLOGY',							'FLAVOR_HAPPINESS',							4							UNION ALL
SELECT								'TECH_THEOLOGY',							'FLAVOR_WONDER',							8							UNION ALL

--EMPIRICISM


SELECT								'TECH_INVENTION',							'FLAVOR_CULTURE',							4							UNION ALL
SELECT								'TECH_INVENTION',							'FLAVOR_PRODUCTION',						7							UNION ALL
SELECT								'TECH_INVENTION',							'FLAVOR_SCIENCE',					        1							UNION ALL
SELECT								'TECH_INVENTION',							'FLAVOR_WONDER',					        8							UNION ALL
SELECT								'TECH_MECHANICS',							'FLAVOR_HAPPINESS',							2							UNION ALL
SELECT								'TECH_MECHANICS',							'FLAVOR_RELIGION',							4							UNION ALL
SELECT								'TECH_MECHANICS',							'FLAVOR_WONDER',							15							UNION ALL
SELECT								'TECH_MECHANICS',							'FLAVOR_CULTURE',							6							UNION ALL
SELECT								'TECH_MECHANICS',							'FLAVOR_PRODUCTION',						2							UNION ALL
SELECT								'TECH_SANITARY_ENGINEERING',				'FLAVOR_EXPANSION',							10							UNION ALL
SELECT								'TECH_SANITARY_ENGINEERING',				'FLAVOR_WONDER',							8							UNION ALL
SELECT								'TECH_SANITARY_ENGINEERING',				'FLAVOR_GROWTH',							15							UNION ALL
SELECT								'TECH_SANITARY_ENGINEERING',				'FLAVOR_SCIENCE',						    5							UNION ALL
SELECT								'TECH_MECHANIC_ARTS',				        'FLAVOR_RELIGION',							2							UNION ALL
SELECT								'TECH_MECHANIC_ARTS',				        'FLAVOR_WONDER',							8							UNION ALL
SELECT								'TECH_MECHANIC_ARTS',				        'FLAVOR_PRODUCTION',						5							UNION ALL
SELECT								'TECH_MECHANIC_ARTS',				        'FLAVOR_MILITARY_TRAINING',					5							UNION ALL

SELECT								'TECH_ENGINEERING',							'FLAVOR_GROWTH',							4							UNION ALL
SELECT								'TECH_ENGINEERING',							'FLAVOR_PRODUCTION',						1							UNION ALL
SELECT								'TECH_ENGINEERING',							'FLAVOR_TILE_IMPROVEMENT',					6							UNION ALL
SELECT								'TECH_ENGINEERING',							'FLAVOR_INFRASTRUCTURE',					4							UNION ALL
SELECT								'TECH_ENGINEERING',							'FLAVOR_WONDER',							2							UNION ALL
SELECT								'TECH_ENGINEERING',							'FLAVOR_EXPANSION',							2							UNION ALL
SELECT								'TECH_METAL_CASTING',						'FLAVOR_PRODUCTION',						8							UNION ALL
SELECT								'TECH_METAL_CASTING',						'FLAVOR_RANGED',							6							UNION ALL
SELECT								'TECH_METAL_CASTING',						'FLAVOR_OFFENSE',							1							UNION ALL
SELECT								'TECH_METAL_CASTING',						'FLAVOR_DEFENSE',							3							UNION ALL
SELECT								'TECH_MACHINERY',							'FLAVOR_GOLD',								7							UNION ALL
SELECT								'TECH_MACHINERY',							'FLAVOR_TILE_IMPROVEMENT',					1							UNION ALL
SELECT								'TECH_MACHINERY',							'FLAVOR_PRODUCTION',						1							UNION ALL
SELECT								'TECH_MACHINERY',							'FLAVOR_INFRASTRUCTURE',					4							UNION ALL
SELECT								'TECH_MACHINERY',							'FLAVOR_DEFENSE',							3							UNION ALL
SELECT								'TECH_MACHINERY',							'FLAVOR_WONDER',							2							UNION ALL
SELECT								'TECH_COMPASS',								'FLAVOR_GOLD',								4							UNION ALL
SELECT								'TECH_COMPASS',								'FLAVOR_NAVAL_TILE_IMPROVEMENT',			2							UNION ALL
SELECT								'TECH_COMPASS',								'FLAVOR_NAVAL',								2							UNION ALL
SELECT								'TECH_COMPASS',								'FLAVOR_WATER_CONNECTION',					8							UNION ALL
SELECT								'TECH_COMPASS',								'FLAVOR_SCIENCE',							2							UNION ALL
SELECT								'TECH_COMPASS',								'FLAVOR_WONDER',							2							UNION ALL
SELECT								'TECH_RUDDER',								'FLAVOR_NAVAL',								12							UNION ALL
SELECT								'TECH_RUDDER',								'FLAVOR_NAVAL_RECON',						4							UNION ALL
SELECT								'TECH_PHYSICS',								'FLAVOR_OFFENSE',							1							UNION ALL
SELECT								'TECH_PHYSICS',								'FLAVOR_WONDER',							4							UNION ALL
SELECT								'TECH_PHYSICS',								'FLAVOR_SCIENCE',							8							UNION ALL
SELECT								'TECH_PHYSICS',								'FLAVOR_GREAT_PEOPLE',						1							UNION ALL
SELECT								'TECH_SIEGE_ENGINES',						'FLAVOR_RANGED',							6							UNION ALL
SELECT								'TECH_SIEGE_ENGINES',						'FLAVOR_OFFENSE',							8							UNION ALL
SELECT								'TECH_SIEGE_ENGINES',						'FLAVOR_DEFENSE',							2							UNION ALL
SELECT								'TECH_SIEGE_ENGINES',						'FLAVOR_MILITARY_TRAINING',					5							UNION ALL



--RENAISSANCE ERA--
--HOMO UNIVERSALIS-




SELECT								'TECH_AESTHETICS',							'FLAVOR_RELIGION',							8							UNION ALL
SELECT								'TECH_AESTHETICS',							'FLAVOR_WONDER',							10							UNION ALL
SELECT								'TECH_AESTHETICS',							'FLAVOR_CULTURE',					        10							UNION ALL
SELECT								'TECH_PSYCHOLOGY',						    'FLAVOR_SCIENCE',							15							UNION ALL
SELECT								'TECH_PSYCHOLOGY',						    'FLAVOR_WONDER',							10							UNION ALL
SELECT								'TECH_REFORMATION',							'FLAVOR_TILE_IMPROVEMENT',					2							UNION ALL
SELECT								'TECH_REFORMATION',						    'FLAVOR_RELIGION',							10							UNION ALL
SELECT								'TECH_REFORMATION',						    'FLAVOR_CULTURE',							6							UNION ALL
SELECT								'TECH_REFORMATION',						    'FLAVOR_WONDER',							10							UNION ALL
SELECT								'TECH_REFORMATION',						    'FLAVOR_HAPPINESS',							2							UNION ALL
SELECT								'TECH_SCHOOLING',							'FLAVOR_SCIENCE',					        10							UNION ALL
SELECT								'TECH_SOCIAL_CLASSES',					    'FLAVOR_CULTURE',							6							UNION ALL
SELECT								'TECH_SOCIAL_CLASSES',					    'FLAVOR_WONDER',							8							UNION ALL
SELECT								'TECH_SOCIAL_CLASSES',					    'FLAVOR_HAPPINESS',							4							UNION ALL

SELECT								'TECH_GUILDS',								'FLAVOR_GOLD',								20							UNION ALL
SELECT								'TECH_GUILDS',								'FLAVOR_WONDER',							2							UNION ALL
SELECT								'TECH_GUILDS',								'FLAVOR_TILE_IMPROVEMENT',					2							UNION ALL
SELECT								'TECH_BANKING',								'FLAVOR_GOLD',								25							UNION ALL
SELECT								'TECH_BANKING',								'FLAVOR_EXPANSION',							2							UNION ALL
SELECT								'TECH_BANKING',								'FLAVOR_HAPPINESS',							4							UNION ALL
SELECT								'TECH_BANKING',								'FLAVOR_WONDER',							2							UNION ALL
SELECT								'TECH_CONSTITUTION',						'FLAVOR_CULTURE',							4							UNION ALL
SELECT								'TECH_CONSTITUTION',						'FLAVOR_HAPPINESS',							4							UNION ALL
SELECT								'TECH_CONSTITUTION',						'FLAVOR_GOLD',								1							UNION ALL
SELECT								'TECH_CONSTITUTION',						'FLAVOR_SCIENCE',							2							UNION ALL
SELECT								'TECH_CONSTITUTION',						'FLAVOR_ESPIONAGE',							4							UNION ALL
SELECT								'TECH_CONSTITUTION',						'FLAVOR_WONDER',							8							UNION ALL
SELECT								'TECH_EDUCATION',							'FLAVOR_SCIENCE',							25							UNION ALL
SELECT								'TECH_EDUCATION',							'FLAVOR_WONDER',							4							UNION ALL
SELECT								'TECH_PRINTING_PRESS',						'FLAVOR_WONDER',							2							UNION ALL
SELECT								'TECH_PRINTING_PRESS',						'FLAVOR_CULTURE',							6							UNION ALL
SELECT								'TECH_PRINTING_PRESS',						'FLAVOR_GREAT_PEOPLE',						8							UNION ALL
SELECT								'TECH_ARCHITECTURE',						'FLAVOR_WONDER',							4							UNION ALL
SELECT								'TECH_ARCHITECTURE',						'FLAVOR_SCIENCE',							8							UNION ALL
SELECT								'TECH_ARCHITECTURE',						'FLAVOR_CULTURE',							4							UNION ALL
SELECT								'TECH_ECONOMICS',							'FLAVOR_GOLD',								18							UNION ALL
SELECT								'TECH_ECONOMICS',							'FLAVOR_WONDER',							4							UNION ALL

--GEOCENTRISM


SELECT								'TECH_MERCANTILISM',						'FLAVOR_GOLD',						        8							UNION ALL
SELECT								'TECH_MERCANTILISM',						'FLAVOR_NAVAL',								2							UNION ALL
SELECT								'TECH_MERCANTILISM',						'FLAVOR_WONDER',							8							UNION ALL
SELECT								'TECH_MERCANTILISM',						'FLAVOR_EXPANSION',							1							UNION ALL
SELECT								'TECH_MERCANTILISM',						'FLAVOR_HAPPINESS',							1							UNION ALL
SELECT							    'TECH_ROMANTICISM',							'FLAVOR_WONDER',							8							UNION ALL
SELECT							    'TECH_ROMANTICISM',							'FLAVOR_CULTURE',							8							UNION ALL
SELECT							    'TECH_HELIOCENTRISM',						'FLAVOR_WONDER',							8							UNION ALL
SELECT							    'TECH_HELIOCENTRISM',					    'FLAVOR_TILE_IMPROVEMENT',					2							UNION ALL
SELECT							    'TECH_HELIOCENTRISM',					    'FLAVOR_CULTURE',							6							UNION ALL
SELECT							    'TECH_HELIOCENTRISM',					    'FLAVOR_DIPLOMACY',							10							UNION ALL
SELECT							    'TECH_NAVAL_TACTICS',						'FLAVOR_WONDER',							8							UNION ALL
SELECT							    'TECH_NAVAL_TACTICS',						'FLAVOR_NAVAL_RECON',					    6							UNION ALL
SELECT							    'TECH_NAVAL_TACTICS',						'FLAVOR_CULTURE',							1							UNION ALL
SELECT							    'TECH_NAVAL_TACTICS',						'FLAVOR_NAVAL',							    10							UNION ALL

SELECT								'TECH_ASTRONOMY',							'FLAVOR_NAVAL_RECON',						10							UNION ALL
SELECT								'TECH_ASTRONOMY',							'FLAVOR_NAVAL',								2							UNION ALL
SELECT								'TECH_ASTRONOMY',							'FLAVOR_SCIENCE',							12							UNION ALL
SELECT								'TECH_ASTRONOMY',							'FLAVOR_EXPANSION',							8							UNION ALL
SELECT								'TECH_ENLIGHTENMENT',						'FLAVOR_GREAT_PEOPLE',						6							UNION ALL
SELECT								'TECH_ENLIGHTENMENT',						'FLAVOR_SCIENCE',							8							UNION ALL
SELECT								'TECH_ENLIGHTENMENT',						'FLAVOR_WONDER',							4							UNION ALL
SELECT								'TECH_EVANGELISM',							'FLAVOR_HAPPINESS',							4							UNION ALL
SELECT								'TECH_EVANGELISM',							'FLAVOR_GOLD',								2							UNION ALL
SELECT								'TECH_EVANGELISM',							'FLAVOR_WONDER',							2							UNION ALL
SELECT								'TECH_EVANGELISM',							'FLAVOR_RELIGION',							10							UNION ALL
SELECT								'TECH_NAVIGATION',							'FLAVOR_NAVAL_RECON',						10							UNION ALL
SELECT								'TECH_NAVIGATION',							'FLAVOR_NAVAL',								22							UNION ALL
SELECT								'TECH_NAVIGATION',							'FLAVOR_WONDER',							2							UNION ALL
SELECT								'TECH_OCEAN_PIONEERING',					'FLAVOR_GOLD',								4						    UNION ALL
SELECT								'TECH_OCEAN_PIONEERING',					'FLAVOR_NAVAL_TILE_IMPROVEMENT',			8							UNION ALL
SELECT								'TECH_OCEAN_PIONEERING',					'FLAVOR_WONDER',							2						    UNION ALL
SELECT								'TECH_OCEAN_PIONEERING',					'FLAVOR_PRODUCTION',						1						    UNION ALL
SELECT								'TECH_INTERNATIONAL_TRADE',					'FLAVOR_GROWTH',							6							UNION ALL
SELECT								'TECH_INTERNATIONAL_TRADE',					'FLAVOR_PRODUCTION',						2							UNION ALL
SELECT								'TECH_INTERNATIONAL_TRADE',					'FLAVOR_SCIENCE',							2							UNION ALL
SELECT								'TECH_INTERNATIONAL_TRADE',					'FLAVOR_GOLD',								6							UNION ALL
SELECT								'TECH_INTERNATIONAL_TRADE',					'FLAVOR_TILE_IMPROVEMENT',					6							UNION ALL

--ALCHEMY

SELECT								'TECH_BATTLEFIELD_MEDICINE',				'FLAVOR_DEFENSE',					        5							UNION ALL
SELECT								'TECH_BATTLEFIELD_MEDICINE',				'FLAVOR_OFFENSE',							5							UNION ALL
SELECT								'TECH_BATTLEFIELD_MEDICINE',				'FLAVOR_MOBILE',							5							UNION ALL
SELECT								'TECH_BATTLEFIELD_MEDICINE',				'FLAVOR_MILITARY_TRAINING',					5							UNION ALL
SELECT								'TECH_CHEMICAL_REVOLUTION',					'FLAVOR_SCIENCE',					        8							UNION ALL
SELECT								'TECH_CHEMICAL_REVOLUTION',					'FLAVOR_GROWTH',							12							UNION ALL
SELECT								'TECH_CHEMICAL_REVOLUTION',					'FLAVOR_WONDER',							9							UNION ALL
SELECT								'TECH_CHEMICAL_REVOLUTION',					'FLAVOR_HAPPINESS',					        2							UNION ALL
SELECT								'TECH_CHEMICAL_REVOLUTION',					'FLAVOR_CULTURE',					        1							UNION ALL





SELECT								'TECH_STEEL',								'FLAVOR_GOLD',								1							UNION ALL
SELECT								'TECH_STEEL',								'FLAVOR_MOBILE',							12							UNION ALL
SELECT								'TECH_STEEL',								'FLAVOR_OFFENSE',							8							UNION ALL
SELECT								'TECH_BLAST_FURNACE',						'FLAVOR_PRODUCTION',						16							UNION ALL
SELECT								'TECH_BLAST_FURNACE',						'FLAVOR_GOLD',								2							UNION ALL
SELECT								'TECH_BLAST_FURNACE',						'FLAVOR_TILE_IMPROVEMENT',					6							UNION ALL
SELECT								'TECH_GUNPOWDER',							'FLAVOR_DEFENSE',							8							UNION ALL
SELECT								'TECH_GUNPOWDER',							'FLAVOR_TILE_IMPROVEMENT',					1							UNION ALL
SELECT								'TECH_GUNPOWDER',							'FLAVOR_GOLD',								1							UNION ALL
SELECT								'TECH_GUNPOWDER',							'FLAVOR_OFFENSE',							10							UNION ALL
SELECT								'TECH_GUNPOWDER',							'FLAVOR_WONDER',							2							UNION ALL
SELECT								'TECH_CHEMISTRY',							'FLAVOR_RANGED',							10							UNION ALL
SELECT								'TECH_CHEMISTRY',							'FLAVOR_OFFENSE',							8							UNION ALL
SELECT								'TECH_CHEMISTRY',							'FLAVOR_DEFENSE',							4							UNION ALL
SELECT								'TECH_FERTILIZER',							'FLAVOR_TILE_IMPROVEMENT',					3							UNION ALL
SELECT								'TECH_FERTILIZER',							'FLAVOR_GROWTH',							12							UNION ALL



--INDUSTRIAL ERA--
--INDUSTRIAL REVOLUTION

SELECT								'TECH_RAILWAY_COMPANY',						'FLAVOR_WONDER',						    8							UNION ALL
SELECT								'TECH_RAILWAY_COMPANY',						'FLAVOR_HAPPINESS',						    6							UNION ALL
SELECT								'TECH_RAILWAY_COMPANY',				        'FLAVOR_TILE_IMPROVEMENT',					2							UNION ALL
SELECT								'TECH_RAILWAY_COMPANY',				        'FLAVOR_CULTURE',					        1							UNION ALL
SELECT								'TECH_PHOTOGRAPHY',					        'FLAVOR_WONDER',						    6							UNION ALL
SELECT								'TECH_PHOTOGRAPHY',					        'FLAVOR_HAPPINESS',						    1							UNION ALL
SELECT								'TECH_PHOTOGRAPHY',				            'FLAVOR_TILE_IMPROVEMENT',					4							UNION ALL
SELECT								'TECH_PHOTOGRAPHY',			                'FLAVOR_CULTURE',					        1							UNION ALL
SELECT								'TECH_TELEGRAPH',					        'FLAVOR_GOLD',						        2							UNION ALL
SELECT								'TECH_TELEGRAPH',				            'FLAVOR_WONDER',					        8							UNION ALL
SELECT								'TECH_TELEGRAPH',			                'FLAVOR_CULTURE',					        2							UNION ALL
SELECT								'TECH_TELEGRAPH',			                'FLAVOR_SCIENCE',					        2							UNION ALL

SELECT								'TECH_STEAM_POWER',							'FLAVOR_NAVAL_RECON',						6							UNION ALL
SELECT								'TECH_STEAM_POWER',							'FLAVOR_PRODUCTION',						6							UNION ALL
SELECT								'TECH_STEAM_POWER',							'FLAVOR_TILE_IMPROVEMENT',					2							UNION ALL
SELECT								'TECH_DYNAMITE',							'FLAVOR_TILE_IMPROVEMENT',					20							UNION ALL
SELECT								'TECH_DYNAMITE',							'FLAVOR_PRODUCTION',						4							UNION ALL
SELECT								'TECH_INDUSTRIALIZATION',					'FLAVOR_PRODUCTION',						25							UNION ALL
SELECT								'TECH_INDUSTRIALIZATION',					'FLAVOR_GOLD',								10							UNION ALL
SELECT								'TECH_INDUSTRIALIZATION',					'FLAVOR_TILE_IMPROVEMENT',					6							UNION ALL
SELECT								'TECH_REPLACEABLE_PARTS',					'FLAVOR_PRODUCTION',						6							UNION ALL
SELECT								'TECH_REPLACEABLE_PARTS',					'FLAVOR_CITY_DEFENSE',						6							UNION ALL
SELECT								'TECH_REPLACEABLE_PARTS',					'FLAVOR_WONDER',							2							UNION ALL
SELECT								'TECH_RAILROAD',							'FLAVOR_INFRASTRUCTURE',					10							UNION ALL
SELECT								'TECH_RAILROAD',							'FLAVOR_PRODUCTION',						4							UNION ALL
SELECT								'TECH_RAILROAD',							'FLAVOR_WONDER',							2							UNION ALL
SELECT								'TECH_RAILROAD',							'FLAVOR_HAPPINESS',							2							UNION ALL
SELECT								'TECH_CORPORATIONS',						'FLAVOR_GOLD',								30							UNION ALL
SELECT								'TECH_CORPORATIONS',						'FLAVOR_TILE_IMPROVEMENT',					6							UNION ALL
SELECT								'TECH_INDUSTRIAL_PROCESSES',				'FLAVOR_GROWTH',							8							UNION ALL
SELECT								'TECH_INDUSTRIAL_PROCESSES',				'FLAVOR_PRODUCTION',						4							UNION ALL
SELECT								'TECH_INDUSTRIAL_PROCESSES',				'FLAVOR_GOLD',								10							UNION ALL
SELECT								'TECH_INDUSTRIAL_PROCESSES',				'FLAVOR_TILE_IMPROVEMENT',					8							UNION ALL
SELECT								'TECH_REFINING',							'FLAVOR_PRODUCTION',						6							UNION ALL
SELECT								'TECH_REFINING',							'FLAVOR_GOLD',								8							UNION ALL
SELECT								'TECH_REFINING',							'FLAVOR_TILE_IMPROVEMENT',					6							UNION ALL

--SCIENCE


SELECT								'TECH_ENERGY_BUILDINGS',					'FLAVOR_PRODUCTION',						15							UNION ALL
SELECT								'TECH_ENERGY_BUILDINGS',					'FLAVOR_SCIENCE',					        5							UNION ALL
SELECT								'TECH_ENERGY_BUILDINGS',					'FLAVOR_EXPANSION',						    10							UNION ALL
SELECT								'TECH_ENERGY_BUILDINGS',					'FLAVOR_INFRASTRUCTURE',					5							UNION ALL
SELECT								'TECH_ENERGY_BUILDINGS',					'FLAVOR_OFFENSE',					        10							UNION ALL
SELECT								'TECH_THERMODYNAMICS',					    'FLAVOR_EXPANSION',						    10							UNION ALL
SELECT								'TECH_THERMODYNAMICS',					    'FLAVOR_INFRASTRUCTURE',					3							UNION ALL
SELECT								'TECH_THERMODYNAMICS',					    'FLAVOR_OFFENSE',					        8							UNION ALL
SELECT								'TECH_THERMODYNAMICS',						'FLAVOR_PRODUCTION',						8							UNION ALL
SELECT								'TECH_THERMODYNAMICS',						'FLAVOR_SCIENCE',					        3							UNION ALL
SELECT								'TECH_NATIONAL_ARTS', 					    'FLAVOR_CULTURE',					        10							UNION ALL
SELECT								'TECH_NATIONAL_ARTS', 						'FLAVOR_WONDER',						    10							UNION ALL
SELECT								'TECH_NATIONAL_ARTS', 						'FLAVOR_RELIGION',					        5							UNION ALL
SELECT								'TECH_TOURISTIC',					        'FLAVOR_CULTURE',					        15							UNION ALL
SELECT								'TECH_TOURISTIC',						    'FLAVOR_WONDER',						    8							UNION ALL
SELECT								'TECH_TOURISTIC',						    'FLAVOR_HAPPINESS',					        10							UNION ALL
SELECT								'TECH_MOTORIZED_TRANSPORTATIONS',		  'FLAVOR_EXPANSION',					        15							UNION ALL
SELECT								'TECH_MOTORIZED_TRANSPORTATIONS',		  'FLAVOR_PRODUCTION',						    15							UNION ALL
SELECT								'TECH_MOTORIZED_TRANSPORTATIONS',		  'FLAVOR_OFFENSE',					            10							UNION ALL
SELECT								'TECH_MOTORIZED_TRANSPORTATIONS',		  'FLAVOR_DEFENSE',					            10							UNION ALL
SELECT								'TECH_MOTORIZED_TRANSPORTATIONS',		  'FLAVOR_AIR',						            10							UNION ALL
SELECT								'TECH_MOTORIZED_TRANSPORTATIONS',		  'FLAVOR_NAVAL',						        10							UNION ALL
SELECT								'TECH_SKYSCRAPER', 		                  'FLAVOR_CULTURE',					            10							UNION ALL
SELECT								'TECH_SKYSCRAPER', 		                  'FLAVOR_WONDER',						        10							UNION ALL
SELECT								'TECH_SKYSCRAPER', 		                  'FLAVOR_GOLD',						        10							UNION ALL
SELECT								'TECH_CRIMINOLOGY',		                  'FLAVOR_SCIENCE',					            6							UNION ALL
SELECT								'TECH_CRIMINOLOGY',			              'FLAVOR_HAPPINESS',						    12							UNION ALL
SELECT								'TECH_CRIMINOLOGY',			              'FLAVOR_DIPLOMACY',						    15							UNION ALL
SELECT								'TECH_MACRO_ENGINEERING', 		          'FLAVOR_PRODUCTION',					         18							UNION ALL
SELECT								'TECH_MACRO_ENGINEERING', 		          'FLAVOR_SCIENCE',						        6							UNION ALL
SELECT								'TECH_MACRO_ENGINEERING', 		          'FLAVOR_INFRASTRUCTURE',						 10							UNION ALL
SELECT								'TECH_MACRO_ENGINEERING', 		          'FLAVOR_TILE_IMPROVEMENT',					 10							UNION ALL
SELECT								'TECH_EXPLORATIONX',		              'FLAVOR_HAPPINESS',						     10							UNION ALL
SELECT								'TECH_EXPLORATIONX',		              'FLAVOR_CULTURE',						         10							UNION ALL
SELECT								'TECH_EXPLORATIONX',		              'FLAVOR_EXPANSION',					         10							UNION ALL
SELECT								'TECH_MEDICINE'		                       'FLAVOR_SCIENCE',						     15							UNION ALL
SELECT								'TECH_MEDICINE'		                       'FLAVOR_GROWTH',						         15							UNION ALL
SELECT								'TECH_MEDICINE'		                       'FLAVOR_EXPANSION',					         10							UNION ALL

SELECT								'TECH_ARCHAEOLOGY',							'FLAVOR_CULTURE',							18							UNION ALL
SELECT								'TECH_ARCHAEOLOGY',							'FLAVOR_WONDER',							2							UNION ALL
SELECT								'TECH_ARCHAEOLOGY',							'FLAVOR_GREAT_PEOPLE',						4							UNION ALL
SELECT								'TECH_BIOLOGY',								'FLAVOR_GROWTH',							8							UNION ALL
SELECT								'TECH_BIOLOGY',								'FLAVOR_TILE_IMPROVEMENT',					10							UNION ALL
SELECT								'TECH_BIOLOGY',								'FLAVOR_OFFENSE',							2							UNION ALL
SELECT								'TECH_BIOLOGY',								'FLAVOR_SCIENCE',							4							UNION ALL
SELECT								'TECH_PHARMACEUTICALS',						'FLAVOR_HAPPINESS',							10							UNION ALL
SELECT								'TECH_PHARMACEUTICALS',						'FLAVOR_WONDER',							4							UNION ALL
SELECT								'TECH_PHARMACEUTICALS',						'FLAVOR_TILE_IMPROVEMENT',					4							UNION ALL
SELECT								'TECH_PHARMACEUTICALS',						'FLAVOR_SCIENCE',							4							UNION ALL
SELECT								'TECH_PHARMACEUTICALS',						'FLAVOR_GOLD',								2							UNION ALL
SELECT								'TECH_SCIENTIFIC_THEORY',					'FLAVOR_SCIENCE',							22							UNION ALL
SELECT								'TECH_SCIENTIFIC_THEORY',					'FLAVOR_WONDER',							2							UNION ALL
SELECT								'TECH_SCIENTIFIC_THEORY',					'FLAVOR_TILE_IMPROVEMENT',					2							UNION ALL
SELECT								'TECH_ELECTRICITY',							'FLAVOR_WONDER',							4							UNION ALL
SELECT								'TECH_ELECTRICITY',							'FLAVOR_PRODUCTION',						12							UNION ALL
SELECT								'TECH_ELECTRICITY',							'FLAVOR_SCIENCE',							4							UNION ALL
SELECT								'TECH_ELECTRICITY',							'FLAVOR_TILE_IMPROVEMENT',					8							UNION ALL
SELECT								'TECH_REFRIGERATION',						'FLAVOR_NAVAL_TILE_IMPROVEMENT',			8							UNION ALL
SELECT								'TECH_REFRIGERATION',						'FLAVOR_GROWTH',							20							UNION ALL

--MILITARY RESEARCH

SELECT								'TECH_WAR_GAMES',							'FLAVOR_DEFENSE',							15						    UNION ALL
SELECT								'TECH_WAR_GAMES',							'FLAVOR_OFFENSE',							15							UNION ALL
SELECT								'TECH_WAR_GAMES',							'FLAVOR_MOBILE',							15						    UNION ALL
SELECT								'TECH_WAR_GAMES',							'FLAVOR_RANGED',							15							UNION ALL
SELECT								'TECH_WAR_GAMES',							'FLAVOR_MILITARY_TRAINING',					10							UNION ALL
SELECT								'TECH_AVIATION',							'FLAVOR_DEFENSE',							15						    UNION ALL
SELECT								'TECH_AVIATION',							'FLAVOR_OFFENSE',							15							UNION ALL
SELECT								'TECH_AVIATION',							'FLAVOR_MOBILE',							15						    UNION ALL
SELECT								'TECH_AVIATION',							'FLAVOR_RANGED',							15							UNION ALL
SELECT								'TECH_AVIATION',							'FLAVOR_WONDER',							5							UNION ALL
SELECT								'TECH_MANEUVER_WARFARE',					'FLAVOR_OFFENSE',							15							UNION ALL
SELECT								'TECH_MANEUVER_WARFARE',					'FLAVOR_MOBILE',							15						    UNION ALL
SELECT								'TECH_MANEUVER_WARFARE',					'FLAVOR_RANGED',							15							UNION ALL
SELECT								'TECH_MANEUVER_WARFARE',					'FLAVOR_MILITARY_TRAINING',					10							UNION ALL

SELECT								'TECH_RIFLING',								'FLAVOR_DEFENSE',							8							UNION ALL
SELECT								'TECH_RIFLING',								'FLAVOR_OFFENSE',							12							UNION ALL
SELECT								'TECH_SHELLS',								'FLAVOR_RANGED',							8							UNION ALL
SELECT								'TECH_SHELLS',								'FLAVOR_OFFENSE',							6							UNION ALL
SELECT								'TECH_SHELLS',								'FLAVOR_DEFENSE',							10							UNION ALL
SELECT								'TECH_NAVAL_ARMOR',							'FLAVOR_NAVAL',								18							UNION ALL
SELECT								'TECH_NAVAL_ARMOR',							'FLAVOR_CITY_DEFENSE',						4							UNION ALL
SELECT								'TECH_MILITARY_TRADITION',					'FLAVOR_MOBILE',							8							UNION ALL
SELECT								'TECH_MILITARY_TRADITION',					'FLAVOR_OFFENSE',							10							UNION ALL
SELECT								'TECH_MILITARY_TRADITION',					'FLAVOR_MILITARY_TRAINING',					5							UNION ALL
SELECT								'TECH_MILITARY_SCIENCE',					'FLAVOR_MILITARY_TRAINING',					16							UNION ALL
SELECT								'TECH_MILITARY_SCIENCE',					'FLAVOR_WONDER',							4							UNION ALL
SELECT								'TECH_BOMBARD',								'FLAVOR_RANGED',							14							UNION ALL
SELECT								'TECH_BOMBARD',								'FLAVOR_OFFENSE',							10							UNION ALL
SELECT								'TECH_BOMBARD',								'FLAVOR_DEFENSE',							8							UNION ALL


-- ELECTRICAL PHENOMENA


SELECT								'TECH_MASS_MEDIA',						    'FLAVOR_CULTURE',							10							UNION ALL
SELECT								'TECH_MASS_MEDIA',							'FLAVOR_HAPPINESS',							10							UNION ALL
SELECT								'TECH_MASS_MEDIA',							'FLAVOR_EXPANSION',							8							UNION ALL
SELECT								'TECH_MASS_TRANSIT',					    'FLAVOR_NAVAL',							   12							UNION ALL
SELECT								'TECH_MASS_TRANSIT',						'FLAVOR_AIR',							   12							UNION ALL
SELECT								'TECH_MASS_TRANSIT',						'FLAVOR_MOBILE',						   12							UNION ALL
SELECT								'TECH_MASS_TRANSIT',					    'FLAVOR_EXPANSION',						   10							UNION ALL

SELECT								'TECH_ENVIRONMENT',  						'FLAVOR_PRODUCTION',						16							UNION ALL
SELECT								'TECH_ENVIRONMENT',  						'FLAVOR_INFRASTRUCTURE',				   10							UNION ALL
SELECT								'TECH_ENVIRONMENT',  						'FLAVOR_MOBILE',						   10							UNION ALL
SELECT								'TECH_ENVIRONMENT',  					    'FLAVOR_TILE_IMPROVEMENT',				  	10						    UNION ALL

SELECT								'TECH_ECO_SYSTEM',  						'FLAVOR_PRODUCTION',				       10							UNION ALL
SELECT								'TECH_ECO_SYSTEM',  						'FLAVOR_MOBILE',						   10							UNION ALL
SELECT								'TECH_ECO_SYSTEM', 					        'FLAVOR_TILE_IMPROVEMENT',				  	10						    UNION ALL
SELECT								'TECH_ECO_SYSTEM',  						'FLAVOR_WONDER',						    8							UNION ALL
SELECT								'TECH_ECO_SYSTEM',   						'FLAVOR_INFRASTRUCTURE',				   10							UNION ALL


SELECT								'TECH_MOTION_PICTURES',  					'FLAVOR_CULTURE',				           10							UNION ALL
SELECT								'TECH_MOTION_PICTURES',  					'FLAVOR_WONDER',						   10							UNION ALL
SELECT								'TECH_MOTION_PICTURES', 					'FLAVOR_HAPPINESS',				  	       4						    UNION ALL
SELECT								'TECH_MOTION_PICTURES',  					'FLAVOR_GREAT_PEOPLE',					   6							UNION ALL
SELECT								'TECH_WORLD_PROJECTS',  					'FLAVOR_DIPLOMACY',				           15							UNION ALL
SELECT								'TECH_WORLD_PROJECTS', 						'FLAVOR_WONDER',				           10							UNION ALL
SELECT								'TECH_WORLD_PROJECTS',  					'FLAVOR_CULTURE',				           10							UNION ALL
SELECT								'TECH_WORLD_PROJECTS', 						'FLAVOR_HAPPINESS',				           6							UNION ALL



	-- AERODYNAMICS

SELECT								'TECH_CITYSCAPE',  					        'FLAVOR_PRODUCTION',				       10							UNION ALL
SELECT								'TECH_CITYSCAPE', 						    'FLAVOR_WONDER',				           10							UNION ALL
SELECT								'TECH_CITYSCAPE',  					        'FLAVOR_CULTURE',				           10							UNION ALL
SELECT								'TECH_CITYSCAPE',						    'FLAVOR_GOLD',				                6							UNION ALL
SELECT								'TECH_SPACE_RESEARCH', 					    'FLAVOR_PRODUCTION',				       10							UNION ALL
SELECT								'TECH_SPACE_RESEARCH', 						'FLAVOR_WONDER',				           10							UNION ALL
SELECT								'TECH_SPACE_RESEARCH', 					    'FLAVOR_SCIENCE',				           15							UNION ALL
SELECT								'TECH_SPACE_RESEARCH',						 'FLAVOR_SPACESHIP',				        6							UNION ALL
SELECT								'TECH_SONAR',        				        'FLAVOR_NAVAL',				               15							UNION ALL
SELECT								'TECH_SONAR',         						'FLAVOR_SCIENCE',				           10							UNION ALL
SELECT								'TECH_SONAR',         					    'FLAVOR_MOBILE',				           10							UNION ALL
SELECT								'TECH_SONAR',        						'FLAVOR_TILE_IMPROVEMENT',				    3							UNION ALL








-- unsorted...




SELECT								'TECH_RADIO','FLAVOR_CULTURE',15							UNION ALL
SELECT								'TECH_RADIO','FLAVOR_WONDER',3							UNION ALL
SELECT								'TECH_FLIGHT','FLAVOR_AIR',15							UNION ALL
SELECT								'TECH_FLIGHT','FLAVOR_ANTIAIR',5							UNION ALL
SELECT								'TECH_BALLISTICS','FLAVOR_OFFENSE',10							UNION ALL
SELECT								'TECH_BALLISTICS','FLAVOR_ANTIAIR',5							UNION ALL
SELECT								'TECH_BALLISTICS','FLAVOR_DEFENSE',10							UNION ALL
SELECT								'TECH_COMBUSTION','FLAVOR_OFFENSE',5							UNION ALL
SELECT								'TECH_COMBUSTION','FLAVOR_MOBILE',2							UNION ALL
SELECT								'TECH_COMBUSTION','FLAVOR_NAVAL',5							UNION ALL
SELECT								'TECH_PLASTIC','FLAVOR_DEFENSE',10							UNION ALL
SELECT								'TECH_PLASTIC','FLAVOR_SCIENCE',5							UNION ALL
SELECT								'TECH_PLASTIC','FLAVOR_SPACESHIP',5							UNION ALL
SELECT								'TECH_ELECTRONICS','FLAVOR_NAVAL',10							UNION ALL
SELECT								'TECH_ELECTRONICS','FLAVOR_OFFENSE',5							UNION ALL
SELECT								'TECH_ELECTRONICS','FLAVOR_AIR_CARRIER',5							UNION ALL
SELECT								'TECH_RADAR','FLAVOR_AIR',15							UNION ALL
SELECT								'TECH_RADAR','FLAVOR_ANTIAIR',5							UNION ALL
SELECT								'TECH_COMBINED_ARMS','FLAVOR_OFFENSE',10							UNION ALL
SELECT								'TECH_COMBINED_ARMS','FLAVOR_MOBILE',10							UNION ALL
SELECT								'TECH_COMBINED_ARMS','FLAVOR_DEFENSE',5							UNION ALL
SELECT								'TECH_THE_ELECTRON','FLAVOR_NUKE',25    UNION ALL
SELECT								'TECH_THE_ELECTRON','FLAVOR_SCIENCE',10						UNION ALL
SELECT								'TECH_THE_ELECTRON','FLAVOR_OFFENSE',10								UNION ALL
SELECT								'TECH_ECOLOGY','FLAVOR_PRODUCTION',8							UNION ALL
SELECT								'TECH_COMPUTERS','FLAVOR_AIR',5							UNION ALL
SELECT								'TECH_COMPUTERS','FLAVOR_NAVAL',5							UNION ALL
SELECT								'TECH_COMPUTERS','FLAVOR_NUKE',5							UNION ALL
SELECT								'TECH_TELECOM','FLAVOR_WONDER',5							UNION ALL
SELECT								'TECH_TELECOM','FLAVOR_DEFENSE',5							UNION ALL
SELECT								'TECH_ROCKETRY','FLAVOR_RANGED',10							UNION ALL
SELECT								'TECH_ROCKETRY','FLAVOR_AIR',5							UNION ALL
SELECT								'TECH_ROCKETRY','FLAVOR_MOBILE',5							UNION ALL
SELECT								'TECH_ROCKETRY','FLAVOR_SPACESHIP',30							UNION ALL
SELECT								'TECH_LASERS','FLAVOR_OFFENSE',5							UNION ALL
SELECT								'TECH_LASERS','FLAVOR_MOBILE',5							UNION ALL
SELECT								'TECH_LASERS','FLAVOR_AIR',5							UNION ALL
SELECT								'TECH_NUCLEAR_FISSION','FLAVOR_NUKE',30							UNION ALL
SELECT								'TECH_NUCLEAR_FISSION','FLAVOR_OFFENSE',5							UNION ALL
SELECT								'TECH_NUCLEAR_FISSION','FLAVOR_PRODUCTION',10							UNION ALL
SELECT								'TECH_GLOBALIZATION','FLAVOR_DIPLOMACY',50							UNION ALL
SELECT								'TECH_ROBOTICS','FLAVOR_NAVAL',4							UNION ALL
SELECT								'TECH_ROBOTICS','FLAVOR_SPACESHIP',25							UNION ALL
SELECT								'TECH_SATELLITES','FLAVOR_SCIENCE',6							UNION ALL
SELECT								'TECH_SATELLITES','FLAVOR_WONDER',2							UNION ALL
SELECT								'TECH_SATELLITES','FLAVOR_SPACESHIP',10							UNION ALL
SELECT								'TECH_STEALTH','FLAVOR_AIR',10							UNION ALL
SELECT								'TECH_MOBILE_TACTICS','FLAVOR_MOBILE',10							UNION ALL
SELECT								'TECH_MOBILE_TACTICS','FLAVOR_DEFENSE',10							UNION ALL
SELECT								'TECH_ADVANCED_BALLISTICS','FLAVOR_NUKE',10							UNION ALL
SELECT								'TECH_ADVANCED_BALLISTICS','FLAVOR_SPACESHIP',10							UNION ALL
SELECT								'TECH_PARTICLE_PHYSICS','FLAVOR_SPACESHIP',20							UNION ALL
SELECT								'TECH_NUCLEAR_FUSION','FLAVOR_OFFENSE',15							UNION ALL
SELECT								'TECH_NUCLEAR_FUSION','FLAVOR_NUKE',5							UNION ALL
SELECT								'TECH_NANOTECHNOLOGY','FLAVOR_SPACESHIP',20							UNION ALL
SELECT								'TECH_FUTURE_TECH','FLAVOR_SCIENCE',10							UNION ALL
SELECT								'TECH_HERDING','FLAVOR_GROWTH',10							UNION ALL
SELECT								'TECH_APOTHECARY','FLAVOR_GROWTH',2							UNION ALL
SELECT								'TECH_APOTHECARY','FLAVOR_GOLD',4							UNION ALL
SELECT								'TECH_APOTHECARY','FLAVOR_SCIENCE',8							UNION ALL

SELECT								'TECH_ANIMAL_MARKETS','FLAVOR_GROWTH',8							UNION ALL
SELECT								'TECH_ANIMAL_MARKETS','FLAVOR_PRODUCTION',2							UNION ALL
SELECT								'TECH_ANIMAL_MARKETS','FLAVOR_GOLD',2							UNION ALL
SELECT								'TECH_FISH_MARKETS','FLAVOR_NAVAL_TILE_IMPROVEMENT',3							UNION ALL
SELECT								'TECH_FISH_MARKETS','FLAVOR_GROWTH',6							UNION ALL
SELECT								'TECH_FISH_MARKETS','FLAVOR_GOLD',6							UNION ALL
SELECT								'TECH_FARMERS_MARKETS','FLAVOR_GROWTH',8							UNION ALL
SELECT								'TECH_FARMERS_MARKETS','FLAVOR_GOLD',3							UNION ALL
SELECT								'TECH_LIVESTOCK_DISTRIBUTION','FLAVOR_GROWTH',10							UNION ALL
SELECT								'TECH_LIVESTOCK_DISTRIBUTION','FLAVOR_PRODUCTION',4							UNION ALL
SELECT								'TECH_LIVESTOCK_DISTRIBUTION','FLAVOR_GOLD',3							UNION ALL
SELECT								'TECH_RAW_MATERIALS','FLAVOR_PRODUCTION',12							UNION ALL
SELECT								'TECH_STONE_MASONS','FLAVOR_PRODUCTION',9							UNION ALL
SELECT								'TECH_STONE_MASONS','FLAVOR_GOLD',3							UNION ALL
SELECT								'TECH_STONE_MASONS','FLAVOR_SCIENCE',2							UNION ALL
SELECT								'TECH_REPLACEABLE_PARTS','FLAVOR_PRODUCTION',6							UNION ALL
SELECT								'TECH_COMBUSTION','FLAVOR_PRODUCTION',9							UNION ALL
SELECT								'TECH_COMBUSTION','FLAVOR_TILE_IMPROVEMENT',2							UNION ALL
SELECT								'TECH_COMBUSTION','FLAVOR_MILITARY_TRAINING',6							UNION ALL
SELECT								'TECH_TORPEDOES','FLAVOR_NAVAL',15							UNION ALL
SELECT								'TECH_TORPEDOES','FLAVOR_NAVAL_RECON',8							UNION ALL
SELECT								'TECH_FLIGHT','FLAVOR_OFFENSE',8							UNION ALL
SELECT								'TECH_FLIGHT','FLAVOR_DEFENSE',5							UNION ALL
SELECT								'TECH_FLIGHT','FLAVOR_MILITARY_TRAINING',6							UNION ALL
SELECT								'TECH_FLIGHT','FLAVOR_PRODUCTION',2							UNION ALL
SELECT								'TECH_TRACKED_VEHICLES','FLAVOR_OFFENSE',15							UNION ALL
SELECT								'TECH_TRACKED_VEHICLES','FLAVOR_DEFENSE',5							UNION ALL
SELECT								'TECH_TRACKED_VEHICLES','FLAVOR_MOBILE',7							UNION ALL
SELECT								'TECH_SUBMERSIBLES','FLAVOR_NAVAL',15							UNION ALL
SELECT								'TECH_SUBMERSIBLES','FLAVOR_NAVAL_RECON',7							UNION ALL
SELECT								'TECH_BIG_GUNS_DOCTRINE','FLAVOR_NAVAL',25							UNION ALL
SELECT								'TECH_RADAR','FLAVOR_DEFENSE',8							UNION ALL
SELECT								'TECH_BLITZKRIEG','FLAVOR_MOBILE',35							UNION ALL
SELECT								'TECH_BLITZKRIEG','FLAVOR_OFFENSE',45							UNION ALL
SELECT								'TECH_ALGEBRA','FLAVOR_WONDER',3							UNION ALL
SELECT								'TECH_ALGEBRA','FLAVOR_SCIENCE',5							UNION ALL
SELECT								'TECH_ALGEBRA','FLAVOR_GREAT_PEOPLE',2							UNION ALL
SELECT								'TECH_CALCULUS','FLAVOR_WONDER',5							UNION ALL
SELECT								'TECH_CALCULUS','FLAVOR_SCIENCE',10							UNION ALL
SELECT								'TECH_AGRICULTURAL_SCIENCES','FLAVOR_GROWTH',20							UNION ALL
SELECT								'TECH_AGRICULTURAL_SCIENCES','FLAVOR_PRODUCTION',5							UNION ALL
SELECT								'TECH_AGRICULTURAL_SCIENCES','FLAVOR_GOLD',5							UNION ALL
SELECT								'TECH_PENICILIN','FLAVOR_MILITARY_TRAINING',2							UNION ALL
SELECT								'TECH_PENICILIN','FLAVOR_OFFENSE',3							UNION ALL
SELECT								'TECH_PENICILIN','FLAVOR_DEFENSE',4							UNION ALL
SELECT								'TECH_TELEPHONE','FLAVOR_GOLD',6							UNION ALL
SELECT								'TECH_TELEPHONE','FLAVOR_WONDER',3							UNION ALL
SELECT								'TECH_TELEPHONE','FLAVOR_SCIENCE',3							UNION ALL
SELECT								'TECH_TELEPHONE','FLAVOR_TILE_IMPROVEMENT',1							UNION ALL
SELECT								'TECH_PLASTIC','FLAVOR_HAPPINESS',7							UNION ALL
SELECT								'TECH_POLYTHEISM','FLAVOR_CULTURE',11							UNION ALL
SELECT								'TECH_POLYTHEISM','FLAVOR_WONDER',5							UNION ALL
SELECT								'TECH_MONOTHEISM','FLAVOR_WONDER',3							UNION ALL
SELECT								'TECH_MONOTHEISM','FLAVOR_CULTURE',6							UNION ALL
SELECT								'TECH_MONOTHEISM','FLAVOR_HAPPINESS',10							UNION ALL
SELECT								'TECH_HERBAL_SCIENCE','FLAVOR_SCIENCE',8							UNION ALL
SELECT								'TECH_HERBAL_SCIENCE','FLAVOR_GOLD',2							UNION ALL
SELECT								'TECH_BUREAUCRACY','FLAVOR_GOLD',15							UNION ALL
SELECT								'TECH_NATIONALISM','FLAVOR_HAPPINESS',4							UNION ALL
SELECT								'TECH_NATIONALISM','FLAVOR_TILE_IMPROVEMENT',3							UNION ALL
SELECT								'TECH_NATIONALISM','FLAVOR_CULTURE',3							UNION ALL
SELECT								'TECH_NATIONALISM','FLAVOR_SCIENCE',3							UNION ALL
SELECT								'TECH_MARXISM','FLAVOR_CULTURE',10							UNION ALL
SELECT								'TECH_MARXISM','FLAVOR_WONDER',3							UNION ALL
SELECT								'TECH_RADIO','FLAVOR_HAPPINESS',15							UNION ALL
SELECT								'TECH_RADIO','FLAVOR_CULTURE',12							UNION ALL
SELECT								'TECH_RADIO','FLAVOR_TILE_IMPROVEMENT',1							UNION ALL
SELECT								'TECH_SOCIALISM','FLAVOR_HAPPINESS',12							UNION ALL
SELECT								'TECH_SOCIALISM','FLAVOR_PRODUCTION',6							UNION ALL
SELECT								'TECH_SOCIALISM','FLAVOR_INFRASTRUCTURE',2							UNION ALL
SELECT								'TECH_ECOLOGY','FLAVOR_HAPPINESS',20;
