INSERT INTO ArtDefine_UnitMemberCombats	(UnitMemberType,							EnableActions,																									DisableActions, MoveRadius, ShortMoveRadius, ChargeRadius, AttackRadius, RangedAttackRadius, MoveRate, ShortMoveRate, TurnRateMin, TurnRateMax, TurnFacingRateMin, TurnFacingRateMax, RollRateMin, RollRateMax, PitchRateMin, PitchRateMax, LOSRadiusScale, TargetRadius, TargetHeight, HasShortRangedAttack,	HasLongRangedAttack,	HasLeftRightAttack, HasStationaryMelee, HasStationaryRangedAttack,	HasRefaceAfterCombat,	ReformBeforeCombat, HasIndependentWeaponFacing, HasOpponentTracking, HasCollisionAttack, AttackAltitude, AltitudeDecelerationDistance, OnlyTurnInMovementActions, RushAttackFormation) VALUES	
										-- Heavy
										('ART_DEF_UNIT_MEMBER_IG_HEAVY',			'Idle Attack RunCharge AttackCity Bombard Death BombardDefend Run Fortify CombatReady Walk AttackCharge',		null,			null,		null,			 null,		   null,		 null,				 null,	   null,		  null,		   null,		null,			   null,			  null,		   null,		null,		  null,			null,			null,		  null,			1,						null,					null,				null,				null,						null,				    1,					null,						null,			     null,				 null,			 null,						   null,					  null),
										-- Sergeant
										('ART_DEF_UNIT_MEMBER_IG_SGT',				'Idle Attack RunCharge AttackCity Bombard Death BombardDefend Run Fortify CombatReady Walk AttackCharge',		null,			null,		null,			 null,		   null,		 null,				 null,	   null,		  null,		   null,		null,			   null,			  null,		   null,		null,		  null,			null,			null,		  null,			null,					null,					null,				null,				null,						null,				    1,					null,						null,			     null,				 null,			 null,						   null,					  null),
										-- Soldier
										('ART_DEF_UNIT_MEMBER_IG_SOLDIER',			'Idle Attack RunCharge AttackCity Bombard Death BombardDefend Run Fortify CombatReady Walk AttackCharge',		null,			null,		null,			 null,		   null,		 null,				 null,	   null,		  null,		   null,		null,			   null,			  null,		   null,		null,		  null,			null,			null,		  null,			1,						null,					null,				null,				null,						null,				    1,					null,						null,			     null,				 null,			 null,						   null,					  null),
										-- Trooper
										('ART_DEF_UNIT_MEMBER_IG_TROOPER',			'Idle Attack RunCharge AttackCity Bombard Death BombardDefend Run Fortify CombatReady Walk AttackCharge',		null,			null,		null,			 null,		   null,		 null,				 null,	   null,		  null,		   null,		null,			   null,			  null,		   null,		null,		  null,			null,			null,		  null,			null,					null,					null,				null,				null,						null,				    1,					null,						null,			     null,				 null,			 null,						   null,					  null),
										-- Vetran
										('ART_DEF_UNIT_MEMBER_IG_VET',				'Idle Attack RunCharge AttackCity Bombard Death BombardDefend Run Fortify CombatReady Walk AttackCharge',		null,			null,		null,			 null,		   null,		 null,				 null,	   null,		  null,		   null,		null,			   null,			  null,		   null,		null,		  null,			null,			null,		  null,			null,					null,					null,				null,				null,						null,				    1,					null,						null,			     null,				 null,			 null,						   null,					  null),
										-- Chimera
										('ART_DEF_UNIT_MEMBER_CHIMERA',				'Idle Attack RunCharge AttackCity Bombard Death BombardDefend Run Fortify CombatReady Walk AttackCharge',		null,			null,		null,			 null,		   null,		 null,				 null,	   null,		  null,		   null,		null,			   null,			  null,		   null,		null,		  null,			null,			null,		  null,			1,						null,					null,				1,					null,						null,				    1,					1,							null,			     null,				 null,			 null,						   null,					  null),
										-- Chimera Dozer
										('ART_DEF_UNIT_MEMBER_CHIMERA_DOZER',		'Idle Attack RunCharge AttackCity Bombard Death BombardDefend Run Fortify CombatReady Walk AttackCharge',		null,			null,		null,			 null,		   null,		 null,				 null,	   null,		  null,		   null,		null,			   null,			  null,		   null,		null,		  null,			null,			null,		  null,			1,						null,					null,				1,					null,						null,				    1,					1,							null,			     null,				 null,			 null,						   null,					  null),
										-- Chimera Vetran
										('ART_DEF_UNIT_MEMBER_CHIMERA_VET',			'Idle Attack RunCharge AttackCity Bombard Death BombardDefend Run Fortify CombatReady Walk AttackCharge',		null,			null,		null,			 null,		   null,		 null,				 null,	   null,		  null,		   null,		null,			   null,			  null,		   null,		null,		  null,			null,			null,		  null,			1,						null,					null,				1,					null,						null,				    1,					1,							null,			     null,				 null,			 null,						   null,					  null),
										-- Banewolf
										('ART_DEF_UNIT_MEMBER_BANEWOLF',			'Idle Attack RunCharge AttackCity Bombard Death BombardDefend Run Fortify CombatReady Walk AttackCharge',		null,			null,		null,			 null,		   null,		 null,				 null,	   null,		  null,		   null,		null,			   null,			  null,		   null,		null,		  null,			null,			null,		  null,			1,						null,					null,				1,					null,						null,				    1,					null,						null,			     null,				 null,			 null,						   null,					  null),
										-- Banewolf SGT
										('ART_DEF_UNIT_MEMBER_BANEWOLF_SGT',		'Idle Attack RunCharge AttackCity Bombard Death BombardDefend Run Fortify CombatReady Walk AttackCharge',		null,			null,		null,			 null,		   null,		 null,				 null,	   null,		  null,		   null,		null,			   null,			  null,		   null,		null,		  null,			null,			null,		  null,			1,						null,					null,				1,					null,						null,				    1,					null,						null,			     null,				 null,			 null,						   null,					  null),
										-- Banewolf Vetran
										('ART_DEF_UNIT_MEMBER_BANEWOLF_VET',		'Idle Attack RunCharge AttackCity Bombard Death BombardDefend Run Fortify CombatReady Walk AttackCharge',		null,			null,		null,			 null,		   null,		 null,				 null,	   null,		  null,		   null,		null,			   null,			  null,		   null,		null,		  null,			null,			null,		  null,			1,						null,					null,				1,					null,						null,				    1,					null,						null,			     null,				 null,			 null,						   null,					  null),
										-- Manticore
										('ART_DEF_UNIT_MEMBER_MANTICORE',			'Idle Attack RunCharge AttackCity Bombard Death BombardDefend Run Fortify CombatReady Walk AttackCharge',		null,			null,		null,			 null,		   null,		 null,				 null,	   null,		  null,		   null,		null,			   null,			  null,		   null,		null,		  null,			null,			null,		  null,			1,						null,					null,				1,					null,						null,				    1,					null,						null,			     null,				 null,			 null,						   null,					  null),
										-- Manticore Dozer
										('ART_DEF_UNIT_MEMBER_MANTICORE_DOZER',		'Idle Attack RunCharge AttackCity Bombard Death BombardDefend Run Fortify CombatReady Walk AttackCharge',		null,			null,		null,			 null,		   null,		 null,				 null,	   null,		  null,		   null,		null,			   null,			  null,		   null,		null,		  null,			null,			null,		  null,			1,						null,					null,				1,					null,						null,				    1,					null,						null,			     null,				 null,			 null,						   null,					  null),
										-- Manticore Vetran
										('ART_DEF_UNIT_MEMBER_MANTICORE_VET',		'Idle Attack RunCharge AttackCity Bombard Death BombardDefend Run Fortify CombatReady Walk AttackCharge',		null,			null,		null,			 null,		   null,		 null,				 null,	   null,		  null,		   null,		null,			   null,			  null,		   null,		null,		  null,			null,			null,		  null,			1,						null,					null,				1,					null,						null,				    1,					null,						null,			     null,				 null,			 null,						   null,					  null),
										-- Baneblade
										('ART_DEF_UNIT_MEMBER_BANEBLADE',			'Idle Attack RunCharge AttackCity Bombard Death BombardDefend Run Fortify CombatReady Walk AttackCharge',		null,			null,		null,			 null,		   null,		 null,				 null,	   null,		  null,		   null,		null,			   null,			  null,		   null,		null,		  null,			null,			null,		  null,			1,						null,					null,				1,					null,						null,				    1,					null,						null,			     null,				 null,			 null,						   null,					  null),
										-- Leman Vanquisher
										('ART_DEF_UNIT_MEMBER_LEMAN_VANQ',			'Idle Attack RunCharge AttackCity Bombard Death BombardDefend Run Fortify CombatReady Walk AttackCharge',		null,			null,		null,			 null,		   null,		 null,				 null,	   null,		  null,		   null,		null,			   null,			  null,		   null,		null,		  null,			null,			null,		  null,			1,						null,					null,				1,					null,						null,				    1,					1,							null,			     null,				 null,			 null,						   null,					  null),
										-- Leman Vanquisher Dozer
										('ART_DEF_UNIT_MEMBER_LEMAN_VANQ_DOZER',	'Idle Attack RunCharge AttackCity Bombard Death BombardDefend Run Fortify CombatReady Walk AttackCharge',		null,			null,		null,			 null,		   null,		 null,				 null,	   null,		  null,		   null,		null,			   null,			  null,		   null,		null,		  null,			null,			null,		  null,			1,						null,					null,				1,					null,						null,				    1,					1,							null,			     null,				 null,			 null,						   null,					  null),
										-- Leman Exec
										('ART_DEF_UNIT_MEMBER_LEMAN_EXEC',			'Idle Attack RunCharge AttackCity Bombard Death BombardDefend Run Fortify CombatReady Walk AttackCharge',		null,			null,		null,			 null,		   null,		 null,				 null,	   null,		  null,		   null,		null,			   null,			  null,		   null,		null,		  null,			null,			null,		  null,			1,						null,					null,				1,					null,						null,				    1,					1,							null,			     null,				 null,			 null,						   null,					  null),
										-- Leman Exec Dozer
										('ART_DEF_UNIT_MEMBER_LEMAN_EXEC_DOZER',	'Idle Attack RunCharge AttackCity Bombard Death BombardDefend Run Fortify CombatReady Walk AttackCharge',		null,			null,		null,			 null,		   null,		 null,				 null,	   null,		  null,		   null,		null,			   null,			  null,		   null,		null,		  null,			null,			null,		  null,			1,						null,					null,				1,					null,						null,				    1,					1,							null,			     null,				 null,			 null,						   null,					  null),
										-- Leman
										('ART_DEF_UNIT_MEMBER_LEMAN',				'Idle Attack RunCharge AttackCity Bombard Death BombardDefend Run Fortify CombatReady Walk AttackCharge',		null,			null,		null,			 null,		   null,		 null,				 null,	   null,		  null,		   null,		null,			   null,			  null,		   null,		null,		  null,			null,			null,		  null,			1,						null,					null,				1,					null,						null,				    1,					1,							null,			     null,				 null,			 null,						   null,					  null),
										-- Leman Dozer
										('ART_DEF_UNIT_MEMBER_LEMAN_DOZER',			'Idle Attack RunCharge AttackCity Bombard Death BombardDefend Run Fortify CombatReady Walk AttackCharge',		null,			null,		null,			 null,		   null,		 null,				 null,	   null,		  null,		   null,		null,			   null,			  null,		   null,		null,		  null,			null,			null,		  null,			1,						null,					null,				1,					null,						null,				    1,					1,							null,			     null,				 null,			 null,						   null,					  null),
										-- Dread
										('ART_DEF_UNIT_MEMBER_DREAD',				'Idle Attack RunCharge AttackCity Bombard Death BombardDefend Run Fortify CombatReady Walk AttackCharge',		null,			null,		null,			 null,		   null,		 null,				 null,	   null,		  null,		   null,		null,			   null,			  null,		   null,		null,		  null,			null,			null,		  null,			1,						1,						null,				null,				null,						null,				    1,					null,						null,			     null,				 null,			 null,						   null,					  null),
										-- Hellfire Dread
										('ART_DEF_UNIT_MEMBER_HELLFIRE_DREAD',		'Idle Attack RunCharge AttackCity Bombard Death BombardDefend Run Fortify CombatReady Walk AttackCharge',		null,			null,		null,			 null,		   null,		 null,				 null,	   null,		  null,		   null,		null,			   null,			  null,		   null,		null,		  null,			null,			null,		  null,			1,						1,						null,				null,				null,						null,				    1,					null,						null,			     null,				 null,			 null,						   null,					  null),
										-- Ven Dread
										('ART_DEF_UNIT_MEMBER_VEN_DREAD',			'Idle Attack RunCharge AttackCity Bombard Death BombardDefend Run Fortify CombatReady Walk AttackCharge',		null,			null,		null,			 null,		   null,		 null,				 null,	   null,		  null,		   null,		null,			   null,			  null,		   null,		null,		  null,			null,			null,		  null,			1,						1,						null,				null,				null,						null,				    1,					null,						null,			     null,				 null,			 null,						   null,					  null);
