-- Insert SQL Rules Here 
INSERT INTO Resource_YieldChanges	(ResourceType,			YieldType,				Yield) VALUES
									('RESOURCE_OAK',		'YIELD_PRODUCTION',		1),
									('RESOURCE_TITANIUM',	'YIELD_PRODUCTION',		1),
									('RESOURCE_ALOE_VERA',	'YIELD_GOLD',			1),
									('RESOURCE_MANGANESE',	'YIELD_PRODUCTION',		1),
									('RESOURCE_TIN',		'YIELD_GOLD',			1),
									('RESOURCE_BERRIES',	'YIELD_FOOD',			1),
									('RESOURCE_FLAX',		'YIELD_GOLD',			1),
									('RESOURCE_COCONUT',	'YIELD_FOOD',			1),
									('RESOURCE_RUBBER',		'YIELD_PRODUCTION',		1),
									('RESOURCE_CACAO',		'YIELD_GOLD',			1),
									('RESOURCE_POPPY',		'YIELD_GOLD',			1),
									('RESOURCE_WOOD',		'YIELD_PRODUCTION',		1),
									('RESOURCE_JADE',		'YIELD_GOLD',			1),
									('RESOURCE_AMBER',		'YIELD_GOLD',			1),
									('RESOURCE_TEA',		'YIELD_GOLD',			1),
									('RESOURCE_RUBBER',		'YIELD_PRODUCTION',		1),
									('RESOURCE_TOBACCO',	'YIELD_GOLD',			1),
									('RESOURCE_CORN',		'YIELD_FOOD',			1),
									('RESOURCE_BARLEY',		'YIELD_FOOD',			1),
									('RESOURCE_MANGO',		'YIELD_FOOD',			1);
